;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_pad_poll
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_put
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_get_pad_new
	.import		_set_scroll_y
	.import		_flush_vram_update2
	.import		_zap_shoot
	.export		_bankLevel
	.export		_bankBuffer
	.import		_set_chr_bank_0
	.export		_pad2_zapper
	.export		_zapper_ready
	.export		_hit_detected
	.export		_cost5
	.export		_cost4
	.export		_cost3
	.export		_cost2
	.export		_cost1
	.export		_cost5_changed
	.export		_cost4_changed
	.export		_cost3_changed
	.export		_cost2_changed
	.export		_cost1_changed
	.export		_gas5
	.export		_gas4
	.export		_gas3
	.export		_gas2
	.export		_gas1
	.export		_gas5_changed
	.export		_gas4_changed
	.export		_gas3_changed
	.export		_gas2_changed
	.export		_gas1_changed
	.export		_gas_speed
	.export		_cost_speed
	.export		_pad1
	.export		_pad1_new
	.export		_trigger_pulled
	.export		_trigger_clicked
	.export		_sprite_cost
	.export		_cost_sprite
	.export		_game_mode
	.export		_pointer
	.export		_temp1
	.export		_temp2
	.export		_address
	.export		_x
	.export		_y
	.export		_num_holder
	.export		_index
	.export		_index2
	.export		_largeindex
	.export		_wram_array
	.export		_adjust_cost
	.export		_adjust_gas
	.export		_draw_cost
	.export		_draw_gas
	.export		_read_input
	.export		_find_sprite
	.export		_init_mode_title
	.export		_init_mode_intro
	.export		_init_mode_game
	.export		_draw_number_as_bg_tile
	.export		_One
	.export		_Two
	.export		_Three
	.export		_Four
	.export		_Five
	.export		_Six
	.export		_Seven
	.export		_Eight
	.export		_Nine
	.export		_Zero
	.export		_metatiles_1
	.export		_room_1
	.export		_level1
	.export		_pal1
	.export		_pal2
	.export		_main

.segment	"DATA"

_index:
	.byte	$00

.segment	"RODATA"

_One:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$20
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$21
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$30
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$31
	.byte	$00
	.byte	$80
_Two:
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$12
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$13
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$22
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$23
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$32
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$33
	.byte	$00
	.byte	$80
_Three:
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$14
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$24
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$25
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$34
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$35
	.byte	$00
	.byte	$80
_Four:
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$16
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$17
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$26
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$27
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$36
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$37
	.byte	$00
	.byte	$80
_Five:
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$19
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$28
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$29
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$38
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$39
	.byte	$00
	.byte	$80
_Six:
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0B
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1A
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1B
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$2A
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$3A
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$3B
	.byte	$00
	.byte	$80
_Seven:
	.byte	$00
	.byte	$00
	.byte	$0C
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0D
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1C
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1D
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$2C
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$2D
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$3C
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$3D
	.byte	$00
	.byte	$80
_Eight:
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1E
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1F
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$2E
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$2F
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$3E
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$3F
	.byte	$00
	.byte	$80
_Nine:
	.byte	$00
	.byte	$00
	.byte	$4E
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$4F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$5E
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$5F
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$6E
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$7E
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$7F
	.byte	$00
	.byte	$80
_Zero:
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$4D
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$5C
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$5D
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$6C
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$6D
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$7C
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$7D
	.byte	$00
	.byte	$80
_metatiles_1:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$C0
	.byte	$C1
	.byte	$D0
	.byte	$D1
	.byte	$01
	.byte	$E0
	.byte	$E1
	.byte	$F0
	.byte	$F1
	.byte	$01
	.byte	$C2
	.byte	$C3
	.byte	$D2
	.byte	$D3
	.byte	$01
	.byte	$E0
	.byte	$E3
	.byte	$F2
	.byte	$F3
	.byte	$01
	.byte	$C4
	.byte	$C5
	.byte	$D4
	.byte	$D5
	.byte	$01
	.byte	$E4
	.byte	$E5
	.byte	$F4
	.byte	$F5
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$00
	.byte	$01
	.byte	$7C
	.byte	$00
	.byte	$5D
	.byte	$7B
	.byte	$01
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$5C
	.byte	$01
	.byte	$7E
	.byte	$5B
	.byte	$7C
	.byte	$7C
	.byte	$01
	.byte	$3C
	.byte	$5C
	.byte	$7D
	.byte	$7C
	.byte	$01
	.byte	$7E
	.byte	$7E
	.byte	$7C
	.byte	$7C
	.byte	$01
	.byte	$7E
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$5B
	.byte	$5C
	.byte	$3E
	.byte	$7F
	.byte	$01
	.byte	$5F
	.byte	$3C
	.byte	$00
	.byte	$7C
	.byte	$01
	.byte	$2F
	.byte	$5B
	.byte	$00
	.byte	$7C
	.byte	$01
	.byte	$5C
	.byte	$5B
	.byte	$7C
	.byte	$7C
	.byte	$01
	.byte	$5C
	.byte	$00
	.byte	$7F
	.byte	$00
	.byte	$01
	.byte	$7C
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5F
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7F
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5B
	.byte	$7B
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$3D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$5D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7C
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$5F
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$5C
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7B
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$00
	.byte	$01
_room_1:
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$12
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$12
	.byte	$10
	.byte	$14
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$01
	.byte	$23
	.byte	$0A
	.byte	$10
	.byte	$14
	.byte	$14
	.byte	$07
	.byte	$02
	.byte	$02
	.byte	$07
	.byte	$0B
	.byte	$0A
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$09
	.byte	$25
	.byte	$24
	.byte	$01
	.byte	$07
	.byte	$01
	.byte	$1A
	.byte	$15
	.byte	$15
	.byte	$15
	.byte	$19
	.byte	$02
	.byte	$0A
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$01
	.byte	$25
	.byte	$01
	.byte	$0B
	.byte	$02
	.byte	$16
	.byte	$28
	.byte	$1F
	.byte	$00
	.byte	$17
	.byte	$23
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$13
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$16
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$17
	.byte	$24
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$04
	.byte	$11
	.byte	$13
	.byte	$01
	.byte	$01
	.byte	$1B
	.byte	$18
	.byte	$00
	.byte	$18
	.byte	$1C
	.byte	$01
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$09
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$26
	.byte	$01
	.byte	$01
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$13
	.byte	$05
	.byte	$0B
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$13
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$25
_level1:
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$13
	.byte	$43
	.byte	$15
	.byte	$16
	.byte	$17
	.byte	$18
	.byte	$19
	.byte	$1A
	.byte	$1B
	.byte	$1C
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$22
	.byte	$23
	.byte	$43
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$28
	.byte	$29
	.byte	$2A
	.byte	$2B
	.byte	$2C
	.byte	$2D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$32
	.byte	$33
	.byte	$43
	.byte	$35
	.byte	$36
	.byte	$37
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$3B
	.byte	$43
	.byte	$3D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$42
	.byte	$43
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$47
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$43
	.byte	$4D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$52
	.byte	$53
	.byte	$54
	.byte	$55
	.byte	$56
	.byte	$57
	.byte	$58
	.byte	$59
	.byte	$5A
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$62
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$73
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$84
	.byte	$85
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$8B
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$91
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$95
	.byte	$96
	.byte	$97
	.byte	$98
	.byte	$99
	.byte	$9A
	.byte	$9B
	.byte	$9C
	.byte	$9D
	.byte	$9E
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$A1
	.byte	$A2
	.byte	$A3
	.byte	$A4
	.byte	$A5
	.byte	$8C
	.byte	$A7
	.byte	$A8
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$AD
	.byte	$AE
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B4
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$BE
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$B0
	.byte	$01
	.byte	$83
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$8C
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$BF
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$B0
	.byte	$81
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$71
	.byte	$9F
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$20
	.byte	$21
	.byte	$30
	.byte	$30
	.byte	$31
	.byte	$40
	.byte	$41
	.byte	$50
	.byte	$01
	.byte	$71
	.byte	$BF
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$90
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$71
	.byte	$BF
	.byte	$61
	.byte	$61
	.byte	$00
	.byte	$00
	.byte	$61
	.byte	$00
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$00
	.byte	$61
	.byte	$00
	.byte	$61
	.byte	$61
	.byte	$A0
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3C
	.byte	$71
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$71
	.byte	$9F
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$71
	.byte	$AF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$01
	.byte	$7D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$71
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$90
	.byte	$81
	.byte	$01
	.byte	$10
	.byte	$31
	.byte	$30
	.byte	$30
	.byte	$21
	.byte	$11
	.byte	$41
	.byte	$50
	.byte	$01
	.byte	$71
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$00
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$71
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3C
	.byte	$71
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$24
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$71
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$24
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$34
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$71
	.byte	$BF
	.byte	$00
	.byte	$70
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$61
	.byte	$00
	.byte	$24
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$34
	.byte	$70
	.byte	$B0
	.byte	$81
	.byte	$01
	.byte	$01
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$01
	.byte	$01
	.byte	$71
	.byte	$AF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B0
	.byte	$01
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$01
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$A2
	.byte	$A3
	.byte	$A4
	.byte	$A5
	.byte	$8C
	.byte	$01
	.byte	$01
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$AD
	.byte	$8D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$61
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B4
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$BE
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$00
	.byte	$00
	.byte	$B0
	.byte	$83
	.byte	$01
	.byte	$82
	.byte	$30
	.byte	$51
	.byte	$31
	.byte	$20
	.byte	$51
	.byte	$20
	.byte	$82
	.byte	$01
	.byte	$01
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B0
	.byte	$01
	.byte	$83
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$7D
	.byte	$BF
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$01
	.byte	$00
	.byte	$45
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$10
	.byte	$00
	.byte	$54
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$55
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$33
	.byte	$80
	.byte	$A0
	.byte	$00
	.byte	$FD
	.byte	$FD
	.byte	$FD
	.byte	$FD
	.byte	$31
	.byte	$08
	.byte	$0A
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$33
	.byte	$88
	.byte	$AA
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$33
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0F
	.byte	$0F
	.byte	$0D
	.byte	$0F
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
_pal1:
	.byte	$0F
	.byte	$05
	.byte	$3D
	.byte	$15
	.byte	$0F
	.byte	$38
	.byte	$21
	.byte	$15
	.byte	$0F
	.byte	$3D
	.byte	$20
	.byte	$11
	.byte	$0F
	.byte	$19
	.byte	$2A
	.byte	$15
_pal2:
	.byte	$0F
	.byte	$3D
	.byte	$20
	.byte	$11
	.byte	$0F
	.byte	$19
	.byte	$2A
	.byte	$15
	.byte	$0F
	.byte	$05
	.byte	$3D
	.byte	$15
	.byte	$0F
	.byte	$38
	.byte	$21
	.byte	$15
L0B3B:
	.byte	$50,$75,$6C,$6C,$20,$74,$68,$65,$20,$74,$72,$69,$67,$67,$65,$72
	.byte	$20,$68,$61,$6C,$66,$77,$61,$79,$00
L0B2A:
	.byte	$50,$75,$6C,$6C,$20,$74,$72,$69,$67,$67,$65,$72,$20,$74,$6F,$20
	.byte	$73,$74,$61,$72,$74,$00
L0B1F:
	.byte	$47,$61,$73,$20,$53,$74,$61,$74,$69,$6F,$6E,$20,$53,$69,$6D,$75
	.byte	$6C,$61,$74,$6F,$72,$00
L0B46:
	.byte	$42,$75,$74,$20,$6E,$6F,$74,$20,$74,$69,$6C,$20,$69,$74,$20,$63
	.byte	$6C,$69,$63,$6B,$73,$00

.segment	"BSS"

_bankLevel:
	.res	1,$00
_bankBuffer:
	.res	10,$00
.segment	"ZEROPAGE"
_pad2_zapper:
	.res	1,$00
_zapper_ready:
	.res	1,$00
_hit_detected:
	.res	1,$00
_cost5:
	.res	1,$00
_cost4:
	.res	1,$00
_cost3:
	.res	1,$00
_cost2:
	.res	1,$00
_cost1:
	.res	1,$00
_cost5_changed:
	.res	1,$00
_cost4_changed:
	.res	1,$00
_cost3_changed:
	.res	1,$00
_cost2_changed:
	.res	1,$00
_cost1_changed:
	.res	1,$00
_gas5:
	.res	1,$00
_gas4:
	.res	1,$00
_gas3:
	.res	1,$00
_gas2:
	.res	1,$00
_gas1:
	.res	1,$00
_gas5_changed:
	.res	1,$00
_gas4_changed:
	.res	1,$00
_gas3_changed:
	.res	1,$00
_gas2_changed:
	.res	1,$00
_gas1_changed:
	.res	1,$00
_gas_speed:
	.res	2,$00
_cost_speed:
	.res	2,$00
_pad1:
	.res	1,$00
_pad1_new:
	.res	1,$00
_trigger_pulled:
	.res	1,$00
_trigger_clicked:
	.res	1,$00
_sprite_cost:
	.res	1,$00
_cost_sprite:
	.res	1,$00
_game_mode:
	.res	1,$00
_pointer:
	.res	2,$00
_temp1:
	.res	1,$00
_temp2:
	.res	1,$00
_address:
	.res	2,$00
_x:
	.res	1,$00
_y:
	.res	1,$00
_num_holder:
	.res	1,$00
_index2:
	.res	1,$00
_largeindex:
	.res	2,$00
.segment	"XRAM"
_wram_array:
	.res	8192,$00

; ---------------------------------------------------------------
; void __near__ adjust_cost (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_adjust_cost: near

.segment	"CODE"

;
; if(cost1 >= 10){
;
	lda     _cost1
	cmp     #$0A
	bcc     L0B73
;
; cost1_changed = 1;
;
	lda     #$01
	sta     _cost1_changed
;
; cost1 = 0;
;
	lda     #$00
	sta     _cost1
;
; ++cost2;
;
	inc     _cost2
;
; if(cost2 >= 10){
;
	lda     _cost2
	cmp     #$0A
	bcc     L0B73
;
; cost2_changed = 1;
;
	lda     #$01
	sta     _cost2_changed
;
; cost2 = 0;
;
	lda     #$00
	sta     _cost2
;
; ++cost3;
;
	inc     _cost3
;
; if(cost3 >= 10){
;
	lda     _cost3
	cmp     #$0A
	bcc     L0B72
;
; cost3_changed = 1;
;
	lda     #$01
	sta     _cost3_changed
;
; cost3 = 0;
;
	lda     #$00
	sta     _cost3
;
; ++cost4;
;
	inc     _cost4
;
; if(cost4 >= 10) {
;
L0B72:	lda     _cost4
	cmp     #$0A
	bcc     L0B73
;
; cost4_changed = 1;
;
	lda     #$01
	sta     _cost4_changed
;
; cost4 = 0;
;
	lda     #$00
	sta     _cost4
;
; ++cost5;
;
	inc     _cost5
;
; if(cost5 >= 10){ // maximum 9999
;
L0B73:	lda     _cost5
	cmp     #$0A
	bcc     L0793
;
; cost5 = 9;
;
	lda     #$09
	sta     _cost5
;
; cost4 = 9;
;
	sta     _cost4
;
; cost3 = 9;
;
	sta     _cost3
;
; cost2 = 9;
;
	sta     _cost2
;
; cost1 = 9;
;
	sta     _cost1
;
; }
;
L0793:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ adjust_gas (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_adjust_gas: near

.segment	"CODE"

;
; if(gas1 >= 10){
;
	lda     _gas1
	cmp     #$0A
	bcc     L0B75
;
; gas1_changed = 1;
;
	lda     #$01
	sta     _gas1_changed
;
; gas1 = 0;
;
	lda     #$00
	sta     _gas1
;
; ++gas2;
;
	inc     _gas2
;
; if(gas2 >= 10){
;
	lda     _gas2
	cmp     #$0A
	bcc     L0B75
;
; gas2_changed = 1;
;
	lda     #$01
	sta     _gas2_changed
;
; gas2 = 0;
;
	lda     #$00
	sta     _gas2
;
; ++gas3;
;
	inc     _gas3
;
; if(gas3 >= 10){
;
	lda     _gas3
	cmp     #$0A
	bcc     L0B74
;
; gas3_changed = 1;
;
	lda     #$01
	sta     _gas3_changed
;
; gas3 = 0;
;
	lda     #$00
	sta     _gas3
;
; ++gas4;
;
	inc     _gas4
;
; if(gas4 >= 10) {
;
L0B74:	lda     _gas4
	cmp     #$0A
	bcc     L0B75
;
; gas4_changed = 1;
;
	lda     #$01
	sta     _gas4_changed
;
; gas4 = 0;
;
	lda     #$00
	sta     _gas4
;
; ++gas5;
;
	inc     _gas5
;
; if(gas5 >= 10){ // maximum 9999
;
L0B75:	lda     _gas5
	cmp     #$0A
	bcc     L076A
;
; gas5 = 9;
;
	lda     #$09
	sta     _gas5
;
; gas4 = 9;
;
	sta     _gas4
;
; gas3 = 9;
;
	sta     _gas3
;
; gas2 = 9;
;
	sta     _gas2
;
; gas1 = 9;
;
	sta     _gas1
;
; }
;
L076A:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_cost (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_cost: near

.segment	"CODE"

;
; if(cost3_changed){
;
	lda     _cost3_changed
	beq     L07A0
;
; num_holder = cost4;
;
	lda     _cost4
	sta     _num_holder
;
; x=21;
;
	lda     #$15
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; cost3_changed = 0;
;
	lda     #$00
	sta     _cost3_changed
;
; if(cost2_changed){
;
L07A0:	lda     _cost2_changed
	beq     L07AB
;
; num_holder = cost3;
;
	lda     _cost3
	sta     _num_holder
;
; x=23;
;
	lda     #$17
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; cost2_changed = 0;
;
	lda     #$00
	sta     _cost2_changed
;
; if(cost1_changed){
;
L07AB:	lda     _cost1_changed
	beq     L07B6
;
; num_holder = cost2;
;
	lda     _cost2
	sta     _num_holder
;
; x=25;
;
	lda     #$19
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; cost1_changed = 0;
;
	lda     #$00
	sta     _cost1_changed
;
; num_holder = cost1;
;
L07B6:	lda     _cost1
	sta     _num_holder
;
; x=27;
;
	lda     #$1B
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jmp     _draw_number_as_bg_tile

.endproc

; ---------------------------------------------------------------
; void __near__ draw_gas (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_gas: near

.segment	"CODE"

;
; if(gas3_changed){
;
	lda     _gas3_changed
	beq     L0AC6
;
; num_holder = gas4;
;
	lda     _gas4
	sta     _num_holder
;
; x=21;
;
	lda     #$15
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; gas3_changed=0;
;
	lda     #$00
	sta     _gas3_changed
;
; if(gas2_changed){
;
L0AC6:	lda     _gas2_changed
	beq     L0AD1
;
; num_holder = gas3;
;
	lda     _gas3
	sta     _num_holder
;
; x=23;
;
	lda     #$17
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; gas2_changed = 0;
;
	lda     #$00
	sta     _gas2_changed
;
; if(gas1_changed){
;
L0AD1:	lda     _gas1_changed
	beq     L0ADC
;
; num_holder = gas2;
;
	lda     _gas2
	sta     _num_holder
;
; x=25;
;
	lda     #$19
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; gas1_changed = 0;
;
	lda     #$00
	sta     _gas1_changed
;
; num_holder = gas1;
;
L0ADC:	lda     _gas1
	sta     _num_holder
;
; x=27;
;
	lda     #$1B
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jmp     _draw_number_as_bg_tile

.endproc

; ---------------------------------------------------------------
; void __near__ read_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_input: near

.segment	"CODE"

;
; pad1 = pad_poll(0);     // read the first controller
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0); // newly pressed button. do pad_poll first
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; trigger_pulled =  (pad1 & PAD_A) || zap_shoot(0); // controller slot 1 zapper
;
	lda     _pad1
	and     #$80
	bne     L0B76
	jsr     _zap_shoot
	tax
	beq     L0B77
L0B76:	lda     #$01
L0B77:	sta     _trigger_pulled
;
; trigger_clicked = (pad1_new & PAD_A);
;
	lda     _pad1_new
	and     #$80
	sta     _trigger_clicked
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ find_sprite (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_find_sprite: near

.segment	"CODE"

;
; switch(sprite_cost) {
;
	lda     _sprite_cost
;
; }
;
	beq     L0AF3
	cmp     #$01
	beq     L0AF7
	cmp     #$02
	beq     L0AFB
	cmp     #$03
	beq     L0AFF
	cmp     #$04
	beq     L0B03
	cmp     #$05
	beq     L0B07
	cmp     #$06
	beq     L0B0B
	cmp     #$07
	beq     L0B0F
	cmp     #$08
	beq     L0B13
	cmp     #$09
	beq     L0B17
	rts
;
; pointer = Zero;
;
L0AF3:	lda     #>(_Zero)
	sta     _pointer+1
	lda     #<(_Zero)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = One;
;
L0AF7:	lda     #>(_One)
	sta     _pointer+1
	lda     #<(_One)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Two;
;
L0AFB:	lda     #>(_Two)
	sta     _pointer+1
	lda     #<(_Two)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Three;
;
L0AFF:	lda     #>(_Three)
	sta     _pointer+1
	lda     #<(_Three)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Four;
;
L0B03:	lda     #>(_Four)
	sta     _pointer+1
	lda     #<(_Four)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Five;
;
L0B07:	lda     #>(_Five)
	sta     _pointer+1
	lda     #<(_Five)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Six;
;
L0B0B:	lda     #>(_Six)
	sta     _pointer+1
	lda     #<(_Six)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Seven;
;
L0B0F:	lda     #>(_Seven)
	sta     _pointer+1
	lda     #<(_Seven)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Eight;
;
L0B13:	lda     #>(_Eight)
	sta     _pointer+1
	lda     #<(_Eight)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Nine;
;
L0B17:	lda     #>(_Nine)
	sta     _pointer+1
	lda     #<(_Nine)
	sta     _pointer
;
; break;
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_mode_title (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_mode_title: near

.segment	"CODE"

;
; ppu_off();  // screen off
;
	jsr     _ppu_off
;
; oam_clear(); // clear all sprites
;
	jsr     _oam_clear
;
; multi_vram_buffer_horz("Gas Station Simulator", 21, NTADR_A(4,4)); 
;
	jsr     decsp3
	lda     #<(L0B1F)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0B1F)
	sta     (sp),y
	lda     #$15
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$84
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; multi_vram_buffer_horz("Pull trigger to start", 21, NTADR_A(4,17)); 
;
	jsr     decsp3
	lda     #<(L0B2A)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0B2A)
	sta     (sp),y
	lda     #$15
	ldy     #$00
	sta     (sp),y
	ldx     #$22
	lda     #$24
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; game_mode=MODE_TITLE;
;
	lda     #$00
	sta     _game_mode
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_mode_intro (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_mode_intro: near

.segment	"CODE"

;
; ppu_off();  // screen off
;
	jsr     _ppu_off
;
; oam_clear(); // clear all sprites
;
	jsr     _oam_clear
;
; multi_vram_buffer_horz("Pull the trigger halfway", 24, NTADR_A(4,4)); 
;
	jsr     decsp3
	lda     #<(L0B3B)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0B3B)
	sta     (sp),y
	lda     #$18
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$84
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; multi_vram_buffer_horz("But not til it clicks", 21, NTADR_A(4,17)); 
;
	jsr     decsp3
	lda     #<(L0B46)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0B46)
	sta     (sp),y
	lda     #$15
	ldy     #$00
	sta     (sp),y
	ldx     #$22
	lda     #$24
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; game_mode=MODE_INTRO;
;
	lda     #$03
	sta     _game_mode
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_mode_game (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_mode_game: near

.segment	"CODE"

;
; set_chr_bank_0(0);
;
	lda     #$00
	jsr     _set_chr_bank_0
;
; ppu_off();  // screen off
;
	jsr     _ppu_off
;
; oam_clear(); // clear all sprites
;
	jsr     _oam_clear
;
; index = 0;
;
	lda     #$00
	sta     _index
;
; vram_adr(0x2000); //Nametable A;
;
	ldx     #$20
	jsr     _vram_adr
;
; for(largeindex = 0; largeindex < 1024; ++largeindex){
;
	lda     #$00
	sta     _largeindex
	sta     _largeindex+1
L0B5C:	lda     _largeindex
	cmp     #$00
	lda     _largeindex+1
	sbc     #$04
	bvc     L0B63
	eor     #$80
L0B63:	bpl     L0B5D
;
; vram_put(level1[largeindex]);
;
	lda     #<(_level1)
	sta     ptr1
	lda     #>(_level1)
	clc
	adc     _largeindex+1
	sta     ptr1+1
	ldy     _largeindex
	lda     (ptr1),y
	jsr     _vram_put
;
; ++index;
;
	inc     _index
;
; if(index > 40) { //don't put too much in the vram_buffer
;
	lda     _index
	cmp     #$29
	bcc     L0B5E
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; index = 0;
;
	lda     #$00
	sta     _index
;
; for(largeindex = 0; largeindex < 1024; ++largeindex){
;
L0B5E:	inc     _largeindex
	bne     L0B5C
	inc     _largeindex+1
	jmp     L0B5C
;
; ppu_on_all(); // turn on screen
;
L0B5D:	jsr     _ppu_on_all
;
; game_mode=MODE_GAME;
;
	lda     #$01
	sta     _game_mode
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_number_as_bg_tile (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_number_as_bg_tile: near

.segment	"CODE"

;
; switch(num_holder) {
;
	lda     _num_holder
;
; }
;
	jeq     L0A79
	cmp     #$01
	beq     L07CD
	cmp     #$02
	jeq     L0819
	cmp     #$03
	jeq     L0865
	cmp     #$04
	jeq     L08B1
	cmp     #$05
	jeq     L08FD
	cmp     #$06
	jeq     L0949
	cmp     #$07
	jeq     L0995
	cmp     #$08
	jeq     L09E1
	cmp     #$09
	jeq     L0A2D
	rts
;
; one_vram_buffer(0xc0, NTADR_A(x,y));
;
L07CD:	lda     #$C0
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc1, NTADR_A(x+1,y));
;
	lda     #$C1
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L07DE
	inx
L07DE:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd0, NTADR_A(x, y+1));
;
	lda     #$D0
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L07E6
	inx
L07E6:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd1, NTADR_A(x+1, y+1));
;
	lda     #$D1
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L07EF
	inx
L07EF:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L07F1
	inx
L07F1:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe0, NTADR_A(x,y+2));
;
	lda     #$E0
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L07F9
	inx
L07F9:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe1, NTADR_A(x+1,y+2));
;
	lda     #$E1
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0802
	inx
L0802:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0804
	inx
L0804:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf0, NTADR_A(x,y+3));
;
	lda     #$F0
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L080C
	inx
L080C:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf1, NTADR_A(x+1,y+3));
;
	lda     #$F1
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0815
	inx
L0815:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0817
	inx
L0817:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc2, NTADR_A(x,y));
;
L0819:	lda     #$C2
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc3, NTADR_A(x+1,y));
;
	lda     #$C3
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L082A
	inx
L082A:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd2, NTADR_A(x, y+1));
;
	lda     #$D2
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0832
	inx
L0832:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd3, NTADR_A(x+1, y+1));
;
	lda     #$D3
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L083B
	inx
L083B:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L083D
	inx
L083D:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe2, NTADR_A(x,y+2));
;
	lda     #$E2
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0845
	inx
L0845:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe3, NTADR_A(x+1,y+2));
;
	lda     #$E3
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L084E
	inx
L084E:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0850
	inx
L0850:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf2, NTADR_A(x,y+3));
;
	lda     #$F2
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0858
	inx
L0858:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf3, NTADR_A(x+1,y+3));
;
	lda     #$F3
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0861
	inx
L0861:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0863
	inx
L0863:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc4, NTADR_A(x,y));
;
L0865:	lda     #$C4
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc5, NTADR_A(x+1,y));
;
	lda     #$C5
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0876
	inx
L0876:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd4, NTADR_A(x, y+1));
;
	lda     #$D4
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L087E
	inx
L087E:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd5, NTADR_A(x+1, y+1));
;
	lda     #$D5
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0887
	inx
L0887:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0889
	inx
L0889:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe4, NTADR_A(x,y+2));
;
	lda     #$E4
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0891
	inx
L0891:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe5, NTADR_A(x+1,y+2));
;
	lda     #$E5
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L089A
	inx
L089A:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L089C
	inx
L089C:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf4, NTADR_A(x,y+3));
;
	lda     #$F4
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L08A4
	inx
L08A4:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf5, NTADR_A(x+1,y+3));
;
	lda     #$F5
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L08AD
	inx
L08AD:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L08AF
	inx
L08AF:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc6, NTADR_A(x,y));
;
L08B1:	lda     #$C6
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc7, NTADR_A(x+1,y));
;
	lda     #$C7
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L08C2
	inx
L08C2:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd6, NTADR_A(x, y+1));
;
	lda     #$D6
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L08CA
	inx
L08CA:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd7, NTADR_A(x+1, y+1));
;
	lda     #$D7
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L08D3
	inx
L08D3:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L08D5
	inx
L08D5:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe6, NTADR_A(x,y+2));
;
	lda     #$E6
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L08DD
	inx
L08DD:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe7, NTADR_A(x+1,y+2));
;
	lda     #$E7
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L08E6
	inx
L08E6:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L08E8
	inx
L08E8:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf6, NTADR_A(x,y+3));
;
	lda     #$F6
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L08F0
	inx
L08F0:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf7, NTADR_A(x+1,y+3));
;
	lda     #$F7
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L08F9
	inx
L08F9:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L08FB
	inx
L08FB:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc8, NTADR_A(x,y));
;
L08FD:	lda     #$C8
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc9, NTADR_A(x+1,y));
;
	lda     #$C9
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L090E
	inx
L090E:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd8, NTADR_A(x, y+1));
;
	lda     #$D8
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0916
	inx
L0916:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd9, NTADR_A(x+1, y+1));
;
	lda     #$D9
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L091F
	inx
L091F:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0921
	inx
L0921:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe8, NTADR_A(x,y+2));
;
	lda     #$E8
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0929
	inx
L0929:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe9, NTADR_A(x+1,y+2));
;
	lda     #$E9
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0932
	inx
L0932:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0934
	inx
L0934:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf8, NTADR_A(x,y+3));
;
	lda     #$F8
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L093C
	inx
L093C:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf9, NTADR_A(x+1,y+3));
;
	lda     #$F9
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0945
	inx
L0945:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0947
	inx
L0947:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xca, NTADR_A(x,y));
;
L0949:	lda     #$CA
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xcb, NTADR_A(x+1,y));
;
	lda     #$CB
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L095A
	inx
L095A:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xda, NTADR_A(x, y+1));
;
	lda     #$DA
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0962
	inx
L0962:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdb, NTADR_A(x+1, y+1));
;
	lda     #$DB
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L096B
	inx
L096B:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L096D
	inx
L096D:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xea, NTADR_A(x,y+2));
;
	lda     #$EA
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0975
	inx
L0975:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xeb, NTADR_A(x+1,y+2));
;
	lda     #$EB
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L097E
	inx
L097E:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0980
	inx
L0980:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfa, NTADR_A(x,y+3));
;
	lda     #$FA
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0988
	inx
L0988:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfb, NTADR_A(x+1,y+3));
;
	lda     #$FB
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0991
	inx
L0991:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0993
	inx
L0993:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xcc, NTADR_A(x,y));
;
L0995:	lda     #$CC
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xcd, NTADR_A(x+1,y));
;
	lda     #$CD
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09A6
	inx
L09A6:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdc, NTADR_A(x, y+1));
;
	lda     #$DC
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L09AE
	inx
L09AE:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdd, NTADR_A(x+1, y+1));
;
	lda     #$DD
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L09B7
	inx
L09B7:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09B9
	inx
L09B9:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xec, NTADR_A(x,y+2));
;
	lda     #$EC
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L09C1
	inx
L09C1:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xed, NTADR_A(x+1,y+2));
;
	lda     #$ED
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L09CA
	inx
L09CA:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09CC
	inx
L09CC:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfc, NTADR_A(x,y+3));
;
	lda     #$FC
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L09D4
	inx
L09D4:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfd, NTADR_A(x+1,y+3));
;
	lda     #$FD
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L09DD
	inx
L09DD:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09DF
	inx
L09DF:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xce, NTADR_A(x,y));
;
L09E1:	lda     #$CE
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xcf, NTADR_A(x+1,y));
;
	lda     #$CF
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09F2
	inx
L09F2:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xde, NTADR_A(x, y+1));
;
	lda     #$DE
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L09FA
	inx
L09FA:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdf, NTADR_A(x+1, y+1));
;
	lda     #$DF
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A03
	inx
L0A03:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A05
	inx
L0A05:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xee, NTADR_A(x,y+2));
;
	lda     #$EE
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A0D
	inx
L0A0D:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xef, NTADR_A(x+1,y+2));
;
	lda     #$EF
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A16
	inx
L0A16:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A18
	inx
L0A18:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfe, NTADR_A(x,y+3));
;
	lda     #$FE
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A20
	inx
L0A20:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xff, NTADR_A(x+1,y+3));
;
	lda     #$FF
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A29
	inx
L0A29:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A2B
	inx
L0A2B:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0x5e, NTADR_A(x,y));
;
L0A2D:	lda     #$5E
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x5f, NTADR_A(x+1,y));
;
	lda     #$5F
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A3E
	inx
L0A3E:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x6e, NTADR_A(x, y+1));
;
	lda     #$6E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A46
	inx
L0A46:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x6f, NTADR_A(x+1, y+1));
;
	lda     #$6F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A4F
	inx
L0A4F:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A51
	inx
L0A51:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x7e, NTADR_A(x,y+2));
;
	lda     #$7E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A59
	inx
L0A59:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x7f, NTADR_A(x+1,y+2));
;
	lda     #$7F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A62
	inx
L0A62:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A64
	inx
L0A64:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x8e, NTADR_A(x,y+3));
;
	lda     #$8E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A6C
	inx
L0A6C:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x8f, NTADR_A(x+1,y+3));
;
	lda     #$8F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A75
	inx
L0A75:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A77
	inx
L0A77:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0x1e, NTADR_A(x,y));
;
L0A79:	lda     #$1E
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x1f, NTADR_A(x+1,y));
;
	lda     #$1F
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A8A
	inx
L0A8A:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x2e, NTADR_A(x, y+1));
;
	lda     #$2E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A92
	inx
L0A92:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x2f, NTADR_A(x+1, y+1));
;
	lda     #$2F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A9B
	inx
L0A9B:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A9D
	inx
L0A9D:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x3e, NTADR_A(x,y+2));
;
	lda     #$3E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0AA5
	inx
L0AA5:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x3f, NTADR_A(x+1,y+2));
;
	lda     #$3F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0AAE
	inx
L0AAE:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0AB0
	inx
L0AB0:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x4e, NTADR_A(x,y+3));
;
	lda     #$4E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0AB8
	inx
L0AB8:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x4f, NTADR_A(x+1,y+3));
;
	lda     #$4F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0AC1
	inx
L0AC1:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0AC3
	inx
L0AC3:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; pal_bg(pal1); // load the palette
;
	lda     #<(_pal1)
	ldx     #>(_pal1)
	jsr     _pal_bg
;
; pal_spr(pal2); // load the palette
;
	lda     #<(_pal2)
	ldx     #>(_pal2)
	jsr     _pal_spr
;
; bank_spr(1); // sprites use the 2nd tileset
;
	lda     #$01
	jsr     _bank_spr
;
; set_scroll_y(0xff); // shift the bg down 1 pixel
;
	ldx     #$00
	lda     #$FF
	jsr     _set_scroll_y
;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; ppu_wait_nmi(); // wait
;
	jsr     _ppu_wait_nmi
;
; set_vram_buffer(); // points ppu update to vram_buffer, do this at least once
;
	jsr     _set_vram_buffer
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; set_chr_bank_0(2);
;
	lda     #$02
	jsr     _set_chr_bank_0
;
; game_mode = MODE_TITLE;
;
	lda     #$00
	sta     _game_mode
;
; init_mode_title();
;
	jsr     _init_mode_title
;
; if(game_mode == MODE_TITLE){
;
L0B78:	lda     _game_mode
	bne     L0B79
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; read_input();
;
	jsr     _read_input
;
; if (trigger_clicked)
;
	lda     _trigger_clicked
	beq     L0B79
;
; init_mode_intro();
;
	jsr     _init_mode_intro
;
; if(game_mode == MODE_INTRO){
;
L0B79:	lda     _game_mode
	cmp     #$03
	bne     L0B7B
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; read_input();
;
	jsr     _read_input
;
; if (trigger_clicked)
;
	lda     _trigger_clicked
	beq     L0B7B
;
; for(index=0; index < 10; ++index){
;
	lda     #$00
	sta     _index
L0B7A:	lda     _index
	cmp     #$0A
	bcs     L0715
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; for(index=0; index < 10; ++index){
;
	inc     _index
	jmp     L0B7A
;
; init_mode_game();
;
L0715:	jsr     _init_mode_game
;
; if(game_mode == MODE_GAME){
;
L0B7B:	lda     _game_mode
	cmp     #$01
	bne     L0B78
;
; ppu_wait_nmi(); // wait till beginning of the frame
;
	jsr     _ppu_wait_nmi
;
; oam_clear();
;
	jsr     _oam_clear
;
; read_input(); //sets input_active
;
	jsr     _read_input
;
; if(trigger_pulled){
;
	lda     _trigger_pulled
	beq     L0723
;
; gas_speed += GAS_STEP;
;
	lda     #$32
	clc
	adc     _gas_speed
	sta     _gas_speed
	bcc     L072A
	inc     _gas_speed+1
;
; while(gas_speed > 256){
;
	jmp     L072A
;
; ++gas1;
;
L0B7C:	inc     _gas1
;
; gas_speed -= 256;
;
	lda     _gas_speed
	sec
	sbc     #$00
	sta     _gas_speed
	lda     _gas_speed+1
	sbc     #$01
	sta     _gas_speed+1
;
; while(gas_speed > 256){
;
L072A:	lda     _gas_speed
	cmp     #$01
	lda     _gas_speed+1
	sbc     #$01
	bcs     L0B7C
;
; adjust_gas();
;
	jsr     _adjust_gas
;
; cost_speed += COST_STEP;
;
	lda     #$50
	clc
	adc     _cost_speed
	sta     _cost_speed
	bcc     L0735
	inc     _cost_speed+1
;
; while(cost_speed > 256){
;
	jmp     L0735
;
; ++cost1;
;
L0B7D:	inc     _cost1
;
; cost_speed -= 256;
;
	lda     _cost_speed
	sec
	sbc     #$00
	sta     _cost_speed
	lda     _cost_speed+1
	sbc     #$01
	sta     _cost_speed+1
;
; while(cost_speed > 256){
;
L0735:	lda     _cost_speed
	cmp     #$01
	lda     _cost_speed+1
	sbc     #$01
	bcs     L0B7D
;
; adjust_cost();
;
	jsr     _adjust_cost
;
; draw_gas();
;
L0723:	jsr     _draw_gas
;
; draw_cost();
;
	jsr     _draw_cost
;
; while (1){
;
	jmp     L0B78

.endproc

