;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_pal_col
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_meta_spr
	.import		_pad_poll
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_put
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_get_pad_new
	.import		_set_scroll_y
	.import		_flush_vram_update2
	.import		_zap_shoot
	.export		_bankLevel
	.export		_bankBuffer
	.import		_set_chr_bank_0
	.import		_set_chr_bank_1
	.export		_pad2_zapper
	.export		_zapper_ready
	.export		_hit_detected
	.export		_cost5
	.export		_cost4
	.export		_cost3
	.export		_cost2
	.export		_cost1
	.export		_cost5_changed
	.export		_cost4_changed
	.export		_cost3_changed
	.export		_cost2_changed
	.export		_cost1_changed
	.export		_gas5
	.export		_gas4
	.export		_gas3
	.export		_gas2
	.export		_gas1
	.export		_gas5_changed
	.export		_gas4_changed
	.export		_gas3_changed
	.export		_gas2_changed
	.export		_gas1_changed
	.export		_gas_speed
	.export		_cost_speed
	.export		_pad1
	.export		_pad1_new
	.export		_trigger_pulled
	.export		_trigger_clicked
	.export		_started_pumping
	.export		_sprite_cost
	.export		_cost_sprite
	.export		_game_mode
	.export		_pointer
	.export		_temp1
	.export		_temp2
	.export		_temp3
	.export		_tempint
	.export		_talking_time
	.export		_bird_x
	.export		_bird_y
	.export		_address
	.export		_x
	.export		_y
	.export		_num_holder
	.export		_index
	.export		_index2
	.export		_largeindex
	.export		_moveframes
	.export		_wram_array
	.export		_adjust_cost
	.export		_adjust_gas
	.export		_draw_cost
	.export		_draw_gas
	.export		_read_input
	.export		_find_sprite
	.export		_init_mode_title
	.export		_init_mode_intro
	.export		_init_mode_game
	.export		_init_level_one_end
	.export		_draw_number_as_bg_tile
	.export		_draw_level_one_sprites
	.export		_draw_talking_time
	.export		_draw_talking_time_background
	.export		_clear_background
	.export		_TurboGut_2
	.export		_BigAlTalk1
	.export		_BigAlTalk2
	.export		_Bird
	.export		_One
	.export		_Two
	.export		_Three
	.export		_Four
	.export		_Five
	.export		_Six
	.export		_Seven
	.export		_Eight
	.export		_Nine
	.export		_Zero
	.export		_metatiles_1
	.export		_room_1
	.export		_level1
	.export		_background_pal
	.export		_pal2
	.export		_talking_time_palete
	.export		_main

.segment	"DATA"

_talking_time:
	.byte	$00
_index:
	.byte	$00

.segment	"RODATA"

_TurboGut_2:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$11
	.byte	$00
	.byte	$80
_BigAlTalk1:
	.byte	$08
	.byte	$30
	.byte	$E1
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$E2
	.byte	$00
	.byte	$18
	.byte	$30
	.byte	$E3
	.byte	$00
	.byte	$20
	.byte	$30
	.byte	$E4
	.byte	$00
	.byte	$28
	.byte	$30
	.byte	$E5
	.byte	$00
	.byte	$30
	.byte	$30
	.byte	$E6
	.byte	$00
	.byte	$80
_BigAlTalk2:
	.byte	$08
	.byte	$30
	.byte	$E1
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$E2
	.byte	$00
	.byte	$18
	.byte	$30
	.byte	$E9
	.byte	$01
	.byte	$20
	.byte	$30
	.byte	$EA
	.byte	$00
	.byte	$28
	.byte	$30
	.byte	$EB
	.byte	$00
	.byte	$30
	.byte	$30
	.byte	$E6
	.byte	$00
	.byte	$80
_Bird:
	.byte	$00
	.byte	$00
	.byte	$A2
	.byte	$20
	.byte	$08
	.byte	$00
	.byte	$A3
	.byte	$20
	.byte	$10
	.byte	$00
	.byte	$A4
	.byte	$20
	.byte	$00
	.byte	$08
	.byte	$B2
	.byte	$20
	.byte	$08
	.byte	$08
	.byte	$B3
	.byte	$20
	.byte	$10
	.byte	$08
	.byte	$B4
	.byte	$20
	.byte	$80
_One:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$20
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$21
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$30
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$31
	.byte	$00
	.byte	$80
_Two:
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$12
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$13
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$22
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$23
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$32
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$33
	.byte	$00
	.byte	$80
_Three:
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$14
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$24
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$25
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$34
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$35
	.byte	$00
	.byte	$80
_Four:
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$16
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$17
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$26
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$27
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$36
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$37
	.byte	$00
	.byte	$80
_Five:
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$19
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$28
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$29
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$38
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$39
	.byte	$00
	.byte	$80
_Six:
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0B
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1A
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1B
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$2A
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$3A
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$3B
	.byte	$00
	.byte	$80
_Seven:
	.byte	$00
	.byte	$00
	.byte	$0C
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0D
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1C
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1D
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$2C
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$2D
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$3C
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$3D
	.byte	$00
	.byte	$80
_Eight:
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1E
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1F
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$2E
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$2F
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$3E
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$3F
	.byte	$00
	.byte	$80
_Nine:
	.byte	$00
	.byte	$00
	.byte	$4E
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$4F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$5E
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$5F
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$6E
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$7E
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$7F
	.byte	$00
	.byte	$80
_Zero:
	.byte	$00
	.byte	$00
	.byte	$4C
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$4D
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$5C
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$5D
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$6C
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$6D
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$7C
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$7D
	.byte	$00
	.byte	$80
_metatiles_1:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$C0
	.byte	$C1
	.byte	$D0
	.byte	$D1
	.byte	$01
	.byte	$E0
	.byte	$E1
	.byte	$F0
	.byte	$F1
	.byte	$01
	.byte	$C2
	.byte	$C3
	.byte	$D2
	.byte	$D3
	.byte	$01
	.byte	$E0
	.byte	$E3
	.byte	$F2
	.byte	$F3
	.byte	$01
	.byte	$C4
	.byte	$C5
	.byte	$D4
	.byte	$D5
	.byte	$01
	.byte	$E4
	.byte	$E5
	.byte	$F4
	.byte	$F5
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$00
	.byte	$01
	.byte	$7C
	.byte	$00
	.byte	$5D
	.byte	$7B
	.byte	$01
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$5C
	.byte	$01
	.byte	$7E
	.byte	$5B
	.byte	$7C
	.byte	$7C
	.byte	$01
	.byte	$3C
	.byte	$5C
	.byte	$7D
	.byte	$7C
	.byte	$01
	.byte	$7E
	.byte	$7E
	.byte	$7C
	.byte	$7C
	.byte	$01
	.byte	$7E
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$5B
	.byte	$5C
	.byte	$3E
	.byte	$7F
	.byte	$01
	.byte	$5F
	.byte	$3C
	.byte	$00
	.byte	$7C
	.byte	$01
	.byte	$2F
	.byte	$5B
	.byte	$00
	.byte	$7C
	.byte	$01
	.byte	$5C
	.byte	$5B
	.byte	$7C
	.byte	$7C
	.byte	$01
	.byte	$5C
	.byte	$00
	.byte	$7F
	.byte	$00
	.byte	$01
	.byte	$7C
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5F
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7F
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5B
	.byte	$7B
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$3D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$5D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7C
	.byte	$00
	.byte	$7C
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$5F
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$5C
	.byte	$00
	.byte	$01
	.byte	$5D
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$7B
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$5E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$00
	.byte	$01
_room_1:
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$12
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$12
	.byte	$10
	.byte	$14
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$01
	.byte	$23
	.byte	$0A
	.byte	$10
	.byte	$14
	.byte	$14
	.byte	$07
	.byte	$02
	.byte	$02
	.byte	$07
	.byte	$0B
	.byte	$0A
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$09
	.byte	$25
	.byte	$24
	.byte	$01
	.byte	$07
	.byte	$01
	.byte	$1A
	.byte	$15
	.byte	$15
	.byte	$15
	.byte	$19
	.byte	$02
	.byte	$0A
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$01
	.byte	$25
	.byte	$01
	.byte	$0B
	.byte	$02
	.byte	$16
	.byte	$28
	.byte	$1F
	.byte	$00
	.byte	$17
	.byte	$23
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$13
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$16
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$17
	.byte	$24
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$04
	.byte	$11
	.byte	$13
	.byte	$01
	.byte	$01
	.byte	$1B
	.byte	$18
	.byte	$00
	.byte	$18
	.byte	$1C
	.byte	$01
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$09
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$26
	.byte	$01
	.byte	$01
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$13
	.byte	$05
	.byte	$0B
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$12
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$13
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$25
_level1:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$23
	.byte	$03
	.byte	$15
	.byte	$16
	.byte	$17
	.byte	$18
	.byte	$19
	.byte	$1A
	.byte	$1B
	.byte	$2C
	.byte	$2D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$32
	.byte	$03
	.byte	$03
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$28
	.byte	$29
	.byte	$2A
	.byte	$2B
	.byte	$03
	.byte	$3D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$03
	.byte	$34
	.byte	$35
	.byte	$36
	.byte	$37
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$3B
	.byte	$03
	.byte	$4D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$03
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$47
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$03
	.byte	$4D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$52
	.byte	$53
	.byte	$54
	.byte	$55
	.byte	$56
	.byte	$57
	.byte	$58
	.byte	$59
	.byte	$5A
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$62
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$73
	.byte	$74
	.byte	$03
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$8B
	.byte	$8C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$91
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$95
	.byte	$96
	.byte	$97
	.byte	$98
	.byte	$99
	.byte	$9A
	.byte	$9B
	.byte	$9C
	.byte	$9D
	.byte	$9E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$A1
	.byte	$A2
	.byte	$A3
	.byte	$A4
	.byte	$A5
	.byte	$01
	.byte	$A7
	.byte	$A8
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$AD
	.byte	$AE
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B4
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$BE
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$B0
	.byte	$01
	.byte	$01
	.byte	$7D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$BF
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$B0
	.byte	$81
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$71
	.byte	$9F
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$B0
	.byte	$81
	.byte	$06
	.byte	$20
	.byte	$21
	.byte	$30
	.byte	$30
	.byte	$31
	.byte	$40
	.byte	$41
	.byte	$50
	.byte	$05
	.byte	$71
	.byte	$BF
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$90
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$1E
	.byte	$1F
	.byte	$02
	.byte	$71
	.byte	$BF
	.byte	$61
	.byte	$61
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$03
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$03
	.byte	$61
	.byte	$61
	.byte	$B0
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$2E
	.byte	$2F
	.byte	$02
	.byte	$3C
	.byte	$AF
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$B0
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$3E
	.byte	$3F
	.byte	$02
	.byte	$4C
	.byte	$9F
	.byte	$02
	.byte	$04
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$04
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$04
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$04
	.byte	$03
	.byte	$03
	.byte	$04
	.byte	$02
	.byte	$B0
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$4E
	.byte	$4F
	.byte	$02
	.byte	$71
	.byte	$AF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$70
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$B0
	.byte	$81
	.byte	$43
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$33
	.byte	$71
	.byte	$BF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$B0
	.byte	$81
	.byte	$06
	.byte	$10
	.byte	$31
	.byte	$30
	.byte	$30
	.byte	$21
	.byte	$11
	.byte	$41
	.byte	$50
	.byte	$05
	.byte	$71
	.byte	$BF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$70
	.byte	$03
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$03
	.byte	$03
	.byte	$70
	.byte	$70
	.byte	$70
	.byte	$B0
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$1E
	.byte	$1F
	.byte	$02
	.byte	$71
	.byte	$9F
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$12
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$90
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$2E
	.byte	$2F
	.byte	$02
	.byte	$3C
	.byte	$BF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$24
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$B0
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$3E
	.byte	$3F
	.byte	$02
	.byte	$4C
	.byte	$BF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$24
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$75
	.byte	$B0
	.byte	$81
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$4E
	.byte	$4F
	.byte	$02
	.byte	$71
	.byte	$BF
	.byte	$03
	.byte	$70
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$03
	.byte	$61
	.byte	$24
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$75
	.byte	$70
	.byte	$90
	.byte	$81
	.byte	$43
	.byte	$01
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$01
	.byte	$33
	.byte	$71
	.byte	$AF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$03
	.byte	$03
	.byte	$B0
	.byte	$01
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$01
	.byte	$BF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$70
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$80
	.byte	$A2
	.byte	$A3
	.byte	$A4
	.byte	$A5
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$AD
	.byte	$8D
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$70
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B4
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$BE
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$70
	.byte	$03
	.byte	$03
	.byte	$B0
	.byte	$01
	.byte	$01
	.byte	$82
	.byte	$30
	.byte	$51
	.byte	$31
	.byte	$20
	.byte	$51
	.byte	$20
	.byte	$82
	.byte	$01
	.byte	$01
	.byte	$BF
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$B0
	.byte	$01
	.byte	$7D
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$7D
	.byte	$BF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$54
	.byte	$55
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$45
	.byte	$05
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$33
	.byte	$A0
	.byte	$A0
	.byte	$20
	.byte	$FA
	.byte	$FE
	.byte	$FE
	.byte	$FE
	.byte	$32
	.byte	$0A
	.byte	$0A
	.byte	$02
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$33
	.byte	$AA
	.byte	$AA
	.byte	$22
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$33
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
_background_pal:
	.byte	$2C
	.byte	$05
	.byte	$3D
	.byte	$15
	.byte	$2C
	.byte	$05
	.byte	$37
	.byte	$15
	.byte	$2C
	.byte	$0F
	.byte	$20
	.byte	$11
	.byte	$2C
	.byte	$19
	.byte	$2A
	.byte	$0F
_pal2:
	.byte	$0F
	.byte	$20
	.byte	$16
	.byte	$36
	.byte	$0F
	.byte	$05
	.byte	$16
	.byte	$36
	.byte	$0F
	.byte	$13
	.byte	$0F
	.byte	$36
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_talking_time_palete:
	.byte	$0F
	.byte	$20
	.byte	$16
	.byte	$36
	.byte	$0F
	.byte	$05
	.byte	$16
	.byte	$36
	.byte	$0F
	.byte	$13
	.byte	$0F
	.byte	$36
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
L0C9D:
	.byte	$50,$75,$6C,$6C,$20,$74,$68,$65,$20,$74,$72,$69,$67,$67,$65,$72
	.byte	$20,$68,$61,$6C,$66,$77,$61,$79,$00
L0C39:
	.byte	$50,$75,$6C,$6C,$20,$74,$72,$69,$67,$67,$65,$72,$20,$74,$6F,$20
	.byte	$73,$74,$61,$72,$74,$00
L0CA8:
	.byte	$42,$75,$74,$20,$6E,$6F,$74,$20,$74,$69,$6C,$20,$69,$74,$20,$63
	.byte	$6C,$69,$63,$6B,$73,$00
L0C2E:
	.byte	$47,$61,$73,$20,$53,$74,$61,$74,$69,$6F,$6E,$20,$53,$69,$6D,$75
	.byte	$6C,$61,$74,$6F,$72,$00
L0C6C:
	.byte	$68,$61,$76,$65,$20,$77,$68,$61,$74,$20,$69,$74,$20,$74,$61,$6B
	.byte	$65,$73,$00
L0C92:
	.byte	$47,$69,$76,$65,$20,$6D,$65,$20,$32,$20,$67,$61,$6C,$6C,$6F,$6E
	.byte	$73,$21,$00
L0C62:
	.byte	$59,$6F,$75,$20,$6A,$75,$73,$74,$20,$64,$6F,$6E,$27,$74,$00
L0C87:
	.byte	$20,$70,$75,$6D,$70,$20,$67,$61,$73,$3F,$21,$3F,$00
L0C7D:
	.byte	$53,$6F,$20,$79,$6F,$75,$20,$77,$61,$6E,$6E,$61,$00
L0C4D:
	.byte	$4E,$69,$63,$65,$20,$57,$6F,$72,$6B,$21,$00
L0C58:
	.byte	$48,$6D,$6D,$6D,$6D,$2E,$2E,$2E,$2E,$00

.segment	"BSS"

_bankLevel:
	.res	1,$00
_bankBuffer:
	.res	10,$00
.segment	"ZEROPAGE"
_pad2_zapper:
	.res	1,$00
_zapper_ready:
	.res	1,$00
_hit_detected:
	.res	1,$00
_cost5:
	.res	1,$00
_cost4:
	.res	1,$00
_cost3:
	.res	1,$00
_cost2:
	.res	1,$00
_cost1:
	.res	1,$00
_cost5_changed:
	.res	1,$00
_cost4_changed:
	.res	1,$00
_cost3_changed:
	.res	1,$00
_cost2_changed:
	.res	1,$00
_cost1_changed:
	.res	1,$00
_gas5:
	.res	1,$00
_gas4:
	.res	1,$00
_gas3:
	.res	1,$00
_gas2:
	.res	1,$00
_gas1:
	.res	1,$00
_gas5_changed:
	.res	1,$00
_gas4_changed:
	.res	1,$00
_gas3_changed:
	.res	1,$00
_gas2_changed:
	.res	1,$00
_gas1_changed:
	.res	1,$00
_gas_speed:
	.res	2,$00
_cost_speed:
	.res	2,$00
_pad1:
	.res	1,$00
_pad1_new:
	.res	1,$00
_trigger_pulled:
	.res	1,$00
_trigger_clicked:
	.res	1,$00
_started_pumping:
	.res	1,$00
_sprite_cost:
	.res	1,$00
_cost_sprite:
	.res	1,$00
_game_mode:
	.res	1,$00
_pointer:
	.res	2,$00
_temp1:
	.res	1,$00
_temp2:
	.res	1,$00
_temp3:
	.res	1,$00
_tempint:
	.res	2,$00
_bird_x:
	.res	1,$00
_bird_y:
	.res	1,$00
_address:
	.res	2,$00
_x:
	.res	1,$00
_y:
	.res	1,$00
_num_holder:
	.res	1,$00
_index2:
	.res	1,$00
_largeindex:
	.res	2,$00
_moveframes:
	.res	1,$00
.segment	"XRAM"
_wram_array:
	.res	8192,$00

; ---------------------------------------------------------------
; void __near__ adjust_cost (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_adjust_cost: near

.segment	"CODE"

;
; if(cost1 >= 10){
;
	lda     _cost1
	cmp     #$0A
	bcc     L0CDE
;
; cost1_changed = 1;
;
	lda     #$01
	sta     _cost1_changed
;
; cost1 = 0;
;
	lda     #$00
	sta     _cost1
;
; ++cost2;
;
	inc     _cost2
;
; if(cost2 >= 10){
;
	lda     _cost2
	cmp     #$0A
	bcc     L0CDE
;
; cost2_changed = 1;
;
	lda     #$01
	sta     _cost2_changed
;
; cost2 = 0;
;
	lda     #$00
	sta     _cost2
;
; ++cost3;
;
	inc     _cost3
;
; if(cost3 >= 10){
;
	lda     _cost3
	cmp     #$0A
	bcc     L0CDD
;
; cost3_changed = 1;
;
	lda     #$01
	sta     _cost3_changed
;
; cost3 = 0;
;
	lda     #$00
	sta     _cost3
;
; ++cost4;
;
	inc     _cost4
;
; if(cost4 >= 10) {
;
L0CDD:	lda     _cost4
	cmp     #$0A
	bcc     L0CDE
;
; cost4_changed = 1;
;
	lda     #$01
	sta     _cost4_changed
;
; cost4 = 0;
;
	lda     #$00
	sta     _cost4
;
; ++cost5;
;
	inc     _cost5
;
; if(cost5 >= 10){ // maximum 9999
;
L0CDE:	lda     _cost5
	cmp     #$0A
	bcc     L0898
;
; cost5 = 9;
;
	lda     #$09
	sta     _cost5
;
; cost4 = 9;
;
	sta     _cost4
;
; cost3 = 9;
;
	sta     _cost3
;
; cost2 = 9;
;
	sta     _cost2
;
; cost1 = 9;
;
	sta     _cost1
;
; }
;
L0898:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ adjust_gas (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_adjust_gas: near

.segment	"CODE"

;
; if(gas1 >= 10){
;
	lda     _gas1
	cmp     #$0A
	bcc     L0CE0
;
; gas1_changed = 1;
;
	lda     #$01
	sta     _gas1_changed
;
; gas1 = 0;
;
	lda     #$00
	sta     _gas1
;
; ++gas2;
;
	inc     _gas2
;
; if(gas2 >= 10){
;
	lda     _gas2
	cmp     #$0A
	bcc     L0CE0
;
; gas2_changed = 1;
;
	lda     #$01
	sta     _gas2_changed
;
; gas2 = 0;
;
	lda     #$00
	sta     _gas2
;
; ++gas3;
;
	inc     _gas3
;
; if(gas3 >= 10){
;
	lda     _gas3
	cmp     #$0A
	bcc     L0CDF
;
; gas3_changed = 1;
;
	lda     #$01
	sta     _gas3_changed
;
; gas3 = 0;
;
	lda     #$00
	sta     _gas3
;
; ++gas4;
;
	inc     _gas4
;
; if(gas4 >= 10) {
;
L0CDF:	lda     _gas4
	cmp     #$0A
	bcc     L0CE0
;
; gas4_changed = 1;
;
	lda     #$01
	sta     _gas4_changed
;
; gas4 = 0;
;
	lda     #$00
	sta     _gas4
;
; ++gas5;
;
	inc     _gas5
;
; if(gas5 >= 10){ // maximum 9999
;
L0CE0:	lda     _gas5
	cmp     #$0A
	bcc     L086F
;
; gas5 = 9;
;
	lda     #$09
	sta     _gas5
;
; gas4 = 9;
;
	sta     _gas4
;
; gas3 = 9;
;
	sta     _gas3
;
; gas2 = 9;
;
	sta     _gas2
;
; gas1 = 9;
;
	sta     _gas1
;
; }
;
L086F:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_cost (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_cost: near

.segment	"CODE"

;
; if(cost3_changed){
;
	lda     _cost3_changed
	beq     L08AF
;
; num_holder = cost4;
;
	lda     _cost4
	sta     _num_holder
;
; x=21;
;
	lda     #$15
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; cost3_changed = 0;
;
	lda     #$00
	sta     _cost3_changed
;
; if(cost2_changed){
;
L08AF:	lda     _cost2_changed
	beq     L08BA
;
; num_holder = cost3;
;
	lda     _cost3
	sta     _num_holder
;
; x=23;
;
	lda     #$17
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; cost2_changed = 0;
;
	lda     #$00
	sta     _cost2_changed
;
; if(cost1_changed){
;
L08BA:	lda     _cost1_changed
	beq     L08C5
;
; num_holder = cost2;
;
	lda     _cost2
	sta     _num_holder
;
; x=25;
;
	lda     #$19
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; cost1_changed = 0;
;
	lda     #$00
	sta     _cost1_changed
;
; num_holder = cost1;
;
L08C5:	lda     _cost1
	sta     _num_holder
;
; x=27;
;
	lda     #$1B
	sta     _x
;
; y=14;
;
	lda     #$0E
	sta     _y
;
; draw_number_as_bg_tile();
;
	jmp     _draw_number_as_bg_tile

.endproc

; ---------------------------------------------------------------
; void __near__ draw_gas (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_gas: near

.segment	"CODE"

;
; if(gas3_changed){
;
	lda     _gas3_changed
	beq     L0BD5
;
; num_holder = gas4;
;
	lda     _gas4
	sta     _num_holder
;
; x=21;
;
	lda     #$15
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; gas3_changed=0;
;
	lda     #$00
	sta     _gas3_changed
;
; if(gas2_changed){
;
L0BD5:	lda     _gas2_changed
	beq     L0BE0
;
; num_holder = gas3;
;
	lda     _gas3
	sta     _num_holder
;
; x=23;
;
	lda     #$17
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; gas2_changed = 0;
;
	lda     #$00
	sta     _gas2_changed
;
; if(gas1_changed){
;
L0BE0:	lda     _gas1_changed
	beq     L0BEB
;
; num_holder = gas2;
;
	lda     _gas2
	sta     _num_holder
;
; x=25;
;
	lda     #$19
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jsr     _draw_number_as_bg_tile
;
; gas1_changed = 0;
;
	lda     #$00
	sta     _gas1_changed
;
; num_holder = gas1;
;
L0BEB:	lda     _gas1
	sta     _num_holder
;
; x=27;
;
	lda     #$1B
	sta     _x
;
; y=20;
;
	lda     #$14
	sta     _y
;
; draw_number_as_bg_tile();
;
	jmp     _draw_number_as_bg_tile

.endproc

; ---------------------------------------------------------------
; void __near__ read_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_input: near

.segment	"CODE"

;
; pad1 = pad_poll(0);     // read the first controller
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0); // newly pressed button. do pad_poll first
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; trigger_pulled =  (pad1 & PAD_A) || zap_shoot(0); // controller slot 1 zapper
;
	lda     _pad1
	and     #$80
	bne     L0CE1
	jsr     _zap_shoot
	tax
	beq     L0CE2
L0CE1:	lda     #$01
L0CE2:	sta     _trigger_pulled
;
; trigger_clicked = (pad1_new & PAD_A);
;
	lda     _pad1_new
	and     #$80
	sta     _trigger_clicked
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ find_sprite (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_find_sprite: near

.segment	"CODE"

;
; switch(sprite_cost) {
;
	lda     _sprite_cost
;
; }
;
	beq     L0C02
	cmp     #$01
	beq     L0C06
	cmp     #$02
	beq     L0C0A
	cmp     #$03
	beq     L0C0E
	cmp     #$04
	beq     L0C12
	cmp     #$05
	beq     L0C16
	cmp     #$06
	beq     L0C1A
	cmp     #$07
	beq     L0C1E
	cmp     #$08
	beq     L0C22
	cmp     #$09
	beq     L0C26
	rts
;
; pointer = Zero;
;
L0C02:	lda     #>(_Zero)
	sta     _pointer+1
	lda     #<(_Zero)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = One;
;
L0C06:	lda     #>(_One)
	sta     _pointer+1
	lda     #<(_One)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Two;
;
L0C0A:	lda     #>(_Two)
	sta     _pointer+1
	lda     #<(_Two)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Three;
;
L0C0E:	lda     #>(_Three)
	sta     _pointer+1
	lda     #<(_Three)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Four;
;
L0C12:	lda     #>(_Four)
	sta     _pointer+1
	lda     #<(_Four)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Five;
;
L0C16:	lda     #>(_Five)
	sta     _pointer+1
	lda     #<(_Five)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Six;
;
L0C1A:	lda     #>(_Six)
	sta     _pointer+1
	lda     #<(_Six)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Seven;
;
L0C1E:	lda     #>(_Seven)
	sta     _pointer+1
	lda     #<(_Seven)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Eight;
;
L0C22:	lda     #>(_Eight)
	sta     _pointer+1
	lda     #<(_Eight)
	sta     _pointer
;
; break;
;
	rts
;
; pointer = Nine;
;
L0C26:	lda     #>(_Nine)
	sta     _pointer+1
	lda     #<(_Nine)
	sta     _pointer
;
; break;
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_mode_title (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_mode_title: near

.segment	"CODE"

;
; ppu_off();  // screen off
;
	jsr     _ppu_off
;
; oam_clear(); // clear all sprites
;
	jsr     _oam_clear
;
; multi_vram_buffer_horz("Gas Station Simulator", 21, NTADR_A(4,16)); 
;
	jsr     decsp3
	lda     #<(L0C2E)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C2E)
	sta     (sp),y
	lda     #$15
	ldy     #$00
	sta     (sp),y
	ldx     #$22
	lda     #$04
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; multi_vram_buffer_horz("Pull trigger to start", 21, NTADR_A(4,17)); 
;
	jsr     decsp3
	lda     #<(L0C39)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C39)
	sta     (sp),y
	lda     #$15
	ldy     #$00
	sta     (sp),y
	ldx     #$22
	lda     #$24
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; game_mode=MODE_TITLE;
;
	lda     #$00
	sta     _game_mode
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_mode_intro (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_mode_intro: near

.segment	"CODE"

;
; ppu_off();  // screen off
;
	jsr     _ppu_off
;
; draw_talking_time_background();
;
	jsr     _draw_talking_time_background
;
; multi_vram_buffer_horz("So you wanna", 12, NTADR_A(15,6)); 
;
	jsr     decsp3
	lda     #<(L0C7D)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C7D)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CF
	jsr     _multi_vram_buffer_horz
;
; multi_vram_buffer_horz(" pump gas?!?", 12, NTADR_A(15,7)); 
;
	jsr     decsp3
	lda     #<(L0C87)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C87)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$EF
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; multi_vram_buffer_horz("Give me 2 gallons!", 18, NTADR_A(13,9)); 
;
	jsr     decsp3
	lda     #<(L0C92)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C92)
	sta     (sp),y
	lda     #$12
	ldy     #$00
	sta     (sp),y
	ldx     #$21
	lda     #$2D
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; multi_vram_buffer_horz("Pull the trigger halfway", 24, NTADR_A(4,16)); 
;
	jsr     decsp3
	lda     #<(L0C9D)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C9D)
	sta     (sp),y
	lda     #$18
	ldy     #$00
	sta     (sp),y
	ldx     #$22
	lda     #$04
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; multi_vram_buffer_horz("But not til it clicks", 21, NTADR_A(4,17)); 
;
	jsr     decsp3
	lda     #<(L0CA8)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0CA8)
	sta     (sp),y
	lda     #$15
	ldy     #$00
	sta     (sp),y
	ldx     #$22
	lda     #$24
	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; game_mode=MODE_INTRO;
;
	lda     #$03
	sta     _game_mode
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_mode_game (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_mode_game: near

.segment	"CODE"

;
; pal_col(0,0x21);
;
	lda     #$00
	jsr     pusha
	lda     #$21
	jsr     _pal_col
;
; pal_bg(background_pal);
;
	lda     #<(_background_pal)
	ldx     #>(_background_pal)
	jsr     _pal_bg
;
; bird_x = 0;
;
	lda     #$00
	sta     _bird_x
;
; set_chr_bank_0(LEVEL1_BG_CHR);
;
	jsr     _set_chr_bank_0
;
; set_chr_bank_1(LEVEL1_FG_CHR);
;
	lda     #$01
	jsr     _set_chr_bank_1
;
; ppu_off();  // screen off
;
	jsr     _ppu_off
;
; oam_clear(); // clear all sprites
;
	jsr     _oam_clear
;
; index = 0;
;
	lda     #$00
	sta     _index
;
; vram_adr(0x2000); //Nametable A;
;
	ldx     #$20
	jsr     _vram_adr
;
; for(largeindex = 0; largeindex < 1024; ++largeindex){
;
	lda     #$00
	sta     _largeindex
	sta     _largeindex+1
L0CC7:	lda     _largeindex
	cmp     #$00
	lda     _largeindex+1
	sbc     #$04
	bvc     L0CCE
	eor     #$80
L0CCE:	bpl     L0CC8
;
; vram_put(level1[largeindex]);
;
	lda     #<(_level1)
	sta     ptr1
	lda     #>(_level1)
	clc
	adc     _largeindex+1
	sta     ptr1+1
	ldy     _largeindex
	lda     (ptr1),y
	jsr     _vram_put
;
; ++index;
;
	inc     _index
;
; if(index > 40) { //don't put too much in the vram_buffer
;
	lda     _index
	cmp     #$29
	bcc     L0CC9
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; index = 0;
;
	lda     #$00
	sta     _index
;
; for(largeindex = 0; largeindex < 1024; ++largeindex){
;
L0CC9:	inc     _largeindex
	bne     L0CC7
	inc     _largeindex+1
	jmp     L0CC7
;
; ppu_on_all(); // turn on screen
;
L0CC8:	jsr     _ppu_on_all
;
; game_mode=MODE_GAME;
;
	lda     #$01
	sta     _game_mode
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_level_one_end (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_level_one_end: near

.segment	"CODE"

;
; ppu_off();  // screen off
;
	jsr     _ppu_off
;
; oam_clear(); // clear all sprites
;
	jsr     _oam_clear
;
; draw_talking_time_background();
;
	jsr     _draw_talking_time_background
;
; if(gas3 == 2){
;
	lda     _gas3
	cmp     #$02
	bne     L0C4A
;
; multi_vram_buffer_horz("Nice Work!", 10, NTADR_A(16,5)); 
;
	jsr     decsp3
	lda     #<(L0C4D)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C4D)
	sta     (sp),y
	lda     #$0A
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$B0
;
; } else {
;
	jmp     L0CE3
;
; multi_vram_buffer_horz("Hmmmm....", 10, NTADR_A(13,5)); 
;
L0C4A:	jsr     decsp3
	lda     #<(L0C58)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C58)
	sta     (sp),y
	lda     #$0A
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$AD
	jsr     _multi_vram_buffer_horz
;
; multi_vram_buffer_horz("You just don't", 14, NTADR_A(13,6)); 
;
	jsr     decsp3
	lda     #<(L0C62)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C62)
	sta     (sp),y
	lda     #$0E
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; multi_vram_buffer_horz("have what it takes", 18, NTADR_A(13,7)); 
;
	jsr     decsp3
	lda     #<(L0C6C)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0C6C)
	sta     (sp),y
	lda     #$12
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$ED
L0CE3:	jsr     _multi_vram_buffer_horz
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; game_mode=MODE_TALKING_TIME;
;
	lda     #$05
	sta     _game_mode
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_number_as_bg_tile (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_number_as_bg_tile: near

.segment	"CODE"

;
; switch(num_holder) {
;
	lda     _num_holder
;
; }
;
	jeq     L0B88
	cmp     #$01
	beq     L08DC
	cmp     #$02
	jeq     L0928
	cmp     #$03
	jeq     L0974
	cmp     #$04
	jeq     L09C0
	cmp     #$05
	jeq     L0A0C
	cmp     #$06
	jeq     L0A58
	cmp     #$07
	jeq     L0AA4
	cmp     #$08
	jeq     L0AF0
	cmp     #$09
	jeq     L0B3C
	rts
;
; one_vram_buffer(0xc0, NTADR_A(x,y));
;
L08DC:	lda     #$C0
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc1, NTADR_A(x+1,y));
;
	lda     #$C1
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L08ED
	inx
L08ED:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd0, NTADR_A(x, y+1));
;
	lda     #$D0
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L08F5
	inx
L08F5:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd1, NTADR_A(x+1, y+1));
;
	lda     #$D1
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L08FE
	inx
L08FE:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0900
	inx
L0900:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe0, NTADR_A(x,y+2));
;
	lda     #$E0
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0908
	inx
L0908:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe1, NTADR_A(x+1,y+2));
;
	lda     #$E1
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0911
	inx
L0911:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0913
	inx
L0913:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf0, NTADR_A(x,y+3));
;
	lda     #$F0
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L091B
	inx
L091B:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf1, NTADR_A(x+1,y+3));
;
	lda     #$F1
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0924
	inx
L0924:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0926
	inx
L0926:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc2, NTADR_A(x,y));
;
L0928:	lda     #$C2
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc3, NTADR_A(x+1,y));
;
	lda     #$C3
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0939
	inx
L0939:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd2, NTADR_A(x, y+1));
;
	lda     #$D2
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0941
	inx
L0941:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd3, NTADR_A(x+1, y+1));
;
	lda     #$D3
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L094A
	inx
L094A:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L094C
	inx
L094C:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe2, NTADR_A(x,y+2));
;
	lda     #$E2
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0954
	inx
L0954:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe3, NTADR_A(x+1,y+2));
;
	lda     #$E3
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L095D
	inx
L095D:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L095F
	inx
L095F:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf2, NTADR_A(x,y+3));
;
	lda     #$F2
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0967
	inx
L0967:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf3, NTADR_A(x+1,y+3));
;
	lda     #$F3
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0970
	inx
L0970:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0972
	inx
L0972:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc4, NTADR_A(x,y));
;
L0974:	lda     #$C4
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc5, NTADR_A(x+1,y));
;
	lda     #$C5
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0985
	inx
L0985:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd4, NTADR_A(x, y+1));
;
	lda     #$D4
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L098D
	inx
L098D:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd5, NTADR_A(x+1, y+1));
;
	lda     #$D5
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0996
	inx
L0996:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0998
	inx
L0998:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe4, NTADR_A(x,y+2));
;
	lda     #$E4
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L09A0
	inx
L09A0:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe5, NTADR_A(x+1,y+2));
;
	lda     #$E5
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L09A9
	inx
L09A9:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09AB
	inx
L09AB:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf4, NTADR_A(x,y+3));
;
	lda     #$F4
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L09B3
	inx
L09B3:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf5, NTADR_A(x+1,y+3));
;
	lda     #$F5
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L09BC
	inx
L09BC:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09BE
	inx
L09BE:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc6, NTADR_A(x,y));
;
L09C0:	lda     #$C6
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc7, NTADR_A(x+1,y));
;
	lda     #$C7
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09D1
	inx
L09D1:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd6, NTADR_A(x, y+1));
;
	lda     #$D6
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L09D9
	inx
L09D9:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd7, NTADR_A(x+1, y+1));
;
	lda     #$D7
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L09E2
	inx
L09E2:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09E4
	inx
L09E4:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe6, NTADR_A(x,y+2));
;
	lda     #$E6
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L09EC
	inx
L09EC:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe7, NTADR_A(x+1,y+2));
;
	lda     #$E7
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L09F5
	inx
L09F5:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L09F7
	inx
L09F7:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf6, NTADR_A(x,y+3));
;
	lda     #$F6
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L09FF
	inx
L09FF:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf7, NTADR_A(x+1,y+3));
;
	lda     #$F7
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A08
	inx
L0A08:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A0A
	inx
L0A0A:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xc8, NTADR_A(x,y));
;
L0A0C:	lda     #$C8
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xc9, NTADR_A(x+1,y));
;
	lda     #$C9
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A1D
	inx
L0A1D:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd8, NTADR_A(x, y+1));
;
	lda     #$D8
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A25
	inx
L0A25:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xd9, NTADR_A(x+1, y+1));
;
	lda     #$D9
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A2E
	inx
L0A2E:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A30
	inx
L0A30:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe8, NTADR_A(x,y+2));
;
	lda     #$E8
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A38
	inx
L0A38:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xe9, NTADR_A(x+1,y+2));
;
	lda     #$E9
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A41
	inx
L0A41:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A43
	inx
L0A43:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf8, NTADR_A(x,y+3));
;
	lda     #$F8
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A4B
	inx
L0A4B:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xf9, NTADR_A(x+1,y+3));
;
	lda     #$F9
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A54
	inx
L0A54:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A56
	inx
L0A56:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xca, NTADR_A(x,y));
;
L0A58:	lda     #$CA
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xcb, NTADR_A(x+1,y));
;
	lda     #$CB
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A69
	inx
L0A69:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xda, NTADR_A(x, y+1));
;
	lda     #$DA
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A71
	inx
L0A71:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdb, NTADR_A(x+1, y+1));
;
	lda     #$DB
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0A7A
	inx
L0A7A:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A7C
	inx
L0A7C:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xea, NTADR_A(x,y+2));
;
	lda     #$EA
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A84
	inx
L0A84:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xeb, NTADR_A(x+1,y+2));
;
	lda     #$EB
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0A8D
	inx
L0A8D:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0A8F
	inx
L0A8F:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfa, NTADR_A(x,y+3));
;
	lda     #$FA
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0A97
	inx
L0A97:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfb, NTADR_A(x+1,y+3));
;
	lda     #$FB
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0AA0
	inx
L0AA0:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0AA2
	inx
L0AA2:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xcc, NTADR_A(x,y));
;
L0AA4:	lda     #$CC
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xcd, NTADR_A(x+1,y));
;
	lda     #$CD
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0AB5
	inx
L0AB5:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdc, NTADR_A(x, y+1));
;
	lda     #$DC
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0ABD
	inx
L0ABD:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdd, NTADR_A(x+1, y+1));
;
	lda     #$DD
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0AC6
	inx
L0AC6:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0AC8
	inx
L0AC8:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xec, NTADR_A(x,y+2));
;
	lda     #$EC
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0AD0
	inx
L0AD0:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xed, NTADR_A(x+1,y+2));
;
	lda     #$ED
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0AD9
	inx
L0AD9:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0ADB
	inx
L0ADB:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfc, NTADR_A(x,y+3));
;
	lda     #$FC
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0AE3
	inx
L0AE3:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfd, NTADR_A(x+1,y+3));
;
	lda     #$FD
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0AEC
	inx
L0AEC:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0AEE
	inx
L0AEE:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0xce, NTADR_A(x,y));
;
L0AF0:	lda     #$CE
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xcf, NTADR_A(x+1,y));
;
	lda     #$CF
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B01
	inx
L0B01:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xde, NTADR_A(x, y+1));
;
	lda     #$DE
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0B09
	inx
L0B09:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xdf, NTADR_A(x+1, y+1));
;
	lda     #$DF
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0B12
	inx
L0B12:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B14
	inx
L0B14:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xee, NTADR_A(x,y+2));
;
	lda     #$EE
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0B1C
	inx
L0B1C:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xef, NTADR_A(x+1,y+2));
;
	lda     #$EF
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0B25
	inx
L0B25:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B27
	inx
L0B27:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xfe, NTADR_A(x,y+3));
;
	lda     #$FE
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0B2F
	inx
L0B2F:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0xff, NTADR_A(x+1,y+3));
;
	lda     #$FF
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0B38
	inx
L0B38:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B3A
	inx
L0B3A:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0x5e, NTADR_A(x,y));
;
L0B3C:	lda     #$5E
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x5f, NTADR_A(x+1,y));
;
	lda     #$5F
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B4D
	inx
L0B4D:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x6e, NTADR_A(x, y+1));
;
	lda     #$6E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0B55
	inx
L0B55:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x6f, NTADR_A(x+1, y+1));
;
	lda     #$6F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0B5E
	inx
L0B5E:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B60
	inx
L0B60:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x7e, NTADR_A(x,y+2));
;
	lda     #$7E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0B68
	inx
L0B68:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x7f, NTADR_A(x+1,y+2));
;
	lda     #$7F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0B71
	inx
L0B71:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B73
	inx
L0B73:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x8e, NTADR_A(x,y+3));
;
	lda     #$8E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0B7B
	inx
L0B7B:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x8f, NTADR_A(x+1,y+3));
;
	lda     #$8F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0B84
	inx
L0B84:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B86
	inx
L0B86:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer
;
; one_vram_buffer(0x1e, NTADR_A(x,y));
;
L0B88:	lda     #$1E
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x1f, NTADR_A(x+1,y));
;
	lda     #$1F
	jsr     pusha
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0B99
	inx
L0B99:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x2e, NTADR_A(x, y+1));
;
	lda     #$2E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0BA1
	inx
L0BA1:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x2f, NTADR_A(x+1, y+1));
;
	lda     #$2F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$01
	bcc     L0BAA
	inx
L0BAA:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0BAC
	inx
L0BAC:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x3e, NTADR_A(x,y+2));
;
	lda     #$3E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0BB4
	inx
L0BB4:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x3f, NTADR_A(x+1,y+2));
;
	lda     #$3F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$02
	bcc     L0BBD
	inx
L0BBD:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0BBF
	inx
L0BBF:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x4e, NTADR_A(x,y+3));
;
	lda     #$4E
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0BC7
	inx
L0BC7:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _x
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x4f, NTADR_A(x+1,y+3));
;
	lda     #$4F
	jsr     pusha
	ldx     #$00
	lda     _y
	clc
	adc     #$03
	bcc     L0BD0
	inx
L0BD0:	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	lda     _x
	clc
	adc     #$01
	bcc     L0BD2
	inx
L0BD2:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ draw_level_one_sprites (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_level_one_sprites: near

.segment	"CODE"

;
; oam_clear();
;
	jsr     _oam_clear
;
; bird_x += 1;
;
	inc     _bird_x
;
; bird_y = 0x20;
;
	lda     #$20
	sta     _bird_y
;
; oam_meta_spr(bird_x,bird_y,Bird);
;
	jsr     decsp2
	lda     _bird_x
	ldy     #$01
	sta     (sp),y
	lda     _bird_y
	dey
	sta     (sp),y
	lda     #<(_Bird)
	ldx     #>(_Bird)
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ draw_talking_time (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_talking_time: near

.segment	"CODE"

;
; temp1 = 0x2044; //vram addr for start of box
;
	lda     #$44
	sta     _temp1
;
; for(temp2 = 0; temp2 < 6; ++temp2){
;
	lda     #$00
	sta     _temp2
L0CE4:	lda     _temp2
	cmp     #$06
	bcs     L0829
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; vram_adr(temp1); //Nametable A starting block
;
	lda     _temp1
	ldx     #$00
	jsr     _vram_adr
;
; for(index = 0; index < 9; ++index){
;
	lda     #$00
	sta     _index
L0CE5:	lda     _index
	cmp     #$09
	bcs     L0834
;
; vram_put(0x00);
;
	lda     #$00
	jsr     _vram_put
;
; for(index = 0; index < 9; ++index){
;
	inc     _index
	jmp     L0CE5
;
; flush_vram_update2();
;
L0834:	jsr     _flush_vram_update2
;
; temp1 += 16;
;
	lda     #$10
	clc
	adc     _temp1
	sta     _temp1
;
; for(temp2 = 0; temp2 < 6; ++temp2){
;
	inc     _temp2
	jmp     L0CE4
;
; flush_vram_update2();
;
L0829:	jsr     _flush_vram_update2
;
; talking_time = 1;
;
	lda     #$01
	sta     _talking_time
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_talking_time_background (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_talking_time_background: near

.segment	"CODE"

;
; set_chr_bank_0(TALKING_TIME_CHR);
;
	lda     #$02
	jsr     _set_chr_bank_0
;
; set_chr_bank_1(TALKING_TIME_CHR);
;
	lda     #$02
	jsr     _set_chr_bank_1
;
; clear_background();
;
	jsr     _clear_background
;
; pal_bg(talking_time_palete);
;
	lda     #<(_talking_time_palete)
	ldx     #>(_talking_time_palete)
	jsr     _pal_bg
;
; tempint = 0x2084;
;
	ldx     #$20
	lda     #$84
	sta     _tempint
	stx     _tempint+1
;
; temp1 = 0x80;
;
	lda     #$80
	sta     _temp1
;
; for(index2 = 0; index2 < 8; ++index2){
;
	lda     #$00
	sta     _index2
L0CE7:	lda     _index2
	cmp     #$08
	bcs     L07FC
;
; vram_adr(tempint);
;
	lda     _tempint
	ldx     _tempint+1
	jsr     _vram_adr
;
; for(index = 0; index < 8; ++index){
;
	lda     #$00
	sta     _index
L0CE8:	lda     _index
	cmp     #$08
	bcs     L0806
;
; vram_put(temp1 + index);
;
	lda     _temp1
	clc
	adc     _index
	jsr     _vram_put
;
; for(index = 0; index < 8; ++index){
;
	inc     _index
	jmp     L0CE8
;
; flush_vram_update2();
;
L0806:	jsr     _flush_vram_update2
;
; temp1 += 16;
;
	lda     #$10
	clc
	adc     _temp1
	sta     _temp1
;
; tempint += 32;
;
	lda     #$20
	clc
	adc     _tempint
	sta     _tempint
	bcc     L0814
	inc     _tempint+1
;
; for(index2 = 0; index2 < 8; ++index2){
;
L0814:	inc     _index2
	jmp     L0CE7
;
; }
;
L07FC:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ clear_background (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_background: near

.segment	"CODE"

;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; for(tempint = 0; tempint < 960; ++tempint){
;
	lda     #$00
	sta     _tempint
	sta     _tempint+1
L0818:	lda     _tempint
	cmp     #$C0
	lda     _tempint+1
	sbc     #$03
	bvc     L081F
	eor     #$80
L081F:	bpl     L0819
;
; vram_put(0x00);
;
	lda     #$00
	jsr     _vram_put
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; for(tempint = 0; tempint < 960; ++tempint){
;
	inc     _tempint
	bne     L0818
	inc     _tempint+1
	jmp     L0818
;
; }
;
L0819:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; moveframes =0;
;
	lda     #$00
	sta     _moveframes
;
; pal_bg(background_pal); // load the palette
;
	lda     #<(_background_pal)
	ldx     #>(_background_pal)
	jsr     _pal_bg
;
; pal_spr(pal2); // load the palette
;
	lda     #<(_pal2)
	ldx     #>(_pal2)
	jsr     _pal_spr
;
; pal_col(0,0x0D);
;
	lda     #$00
	jsr     pusha
	lda     #$0D
	jsr     _pal_col
;
; bank_spr(1); // sprites use the 2nd tileset
;
	lda     #$01
	jsr     _bank_spr
;
; set_scroll_y(0xff); // shift the bg down 1 pixel
;
	ldx     #$00
	lda     #$FF
	jsr     _set_scroll_y
;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; ppu_wait_nmi(); // wait
;
	jsr     _ppu_wait_nmi
;
; set_vram_buffer(); // points ppu update to vram_buffer, do this at least once
;
	jsr     _set_vram_buffer
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; game_mode = MODE_TITLE;
;
	lda     #$00
	sta     _game_mode
;
; init_mode_title();
;
	jsr     _init_mode_title
;
; if(game_mode == MODE_TITLE){
;
L0CE9:	lda     _game_mode
	bne     L0CEA
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; read_input();
;
	jsr     _read_input
;
; if (trigger_clicked)
;
	lda     _trigger_clicked
	beq     L0CEA
;
; init_mode_intro();
;
	jsr     _init_mode_intro
;
; if(game_mode == MODE_INTRO){
;
L0CEA:	lda     _game_mode
	cmp     #$03
	bne     L0CF1
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; ++moveframes;
;
	inc     _moveframes
;
; if(moveframes > 60){
;
	lda     _moveframes
	cmp     #$3D
	bcc     L0782
;
; moveframes = 0;
;
	lda     #$00
	sta     _moveframes
;
; oam_clear(); // clear all sprites
;
L0782:	jsr     _oam_clear
;
; if(moveframes >= 0 && moveframes < 30){
;
	lda     _moveframes
	cmp     #$1E
	bcs     L0CEC
;
; oam_meta_spr(0x20, 0x20, BigAlTalk1);
;
	jsr     decsp2
	lda     #$20
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_BigAlTalk1)
	ldx     #>(_BigAlTalk1)
	jsr     _oam_meta_spr
;
; if(moveframes >= 30 && moveframes < 61){
;
L0CEC:	lda     _moveframes
	cmp     #$1E
	bcc     L078F
	cmp     #$3D
	bcs     L078F
;
; oam_meta_spr(0x20, 0x20, BigAlTalk2);
;
	jsr     decsp2
	lda     #$20
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_BigAlTalk2)
	ldx     #>(_BigAlTalk2)
	jsr     _oam_meta_spr
;
; read_input();
;
L078F:	jsr     _read_input
;
; if (trigger_clicked)
;
	lda     _trigger_clicked
	beq     L0CF1
;
; for(index=0; index < 10; ++index){
;
	lda     #$00
	sta     _index
L0CF0:	lda     _index
	cmp     #$0A
	bcs     L079B
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; for(index=0; index < 10; ++index){
;
	inc     _index
	jmp     L0CF0
;
; init_mode_game();
;
L079B:	jsr     _init_mode_game
;
; if(game_mode == MODE_TALKING_TIME){
;
L0CF1:	lda     _game_mode
	cmp     #$05
	bne     L0CF8
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; ++moveframes;
;
	inc     _moveframes
;
; if(moveframes > 60){
;
	lda     _moveframes
	cmp     #$3D
	bcc     L07A8
;
; moveframes = 0;
;
	lda     #$00
	sta     _moveframes
;
; oam_clear(); // clear all sprites
;
L07A8:	jsr     _oam_clear
;
; if(moveframes >= 0 && moveframes < 30){
;
	lda     _moveframes
	cmp     #$1E
	bcs     L0CF3
;
; oam_meta_spr(0x20, 0x20, BigAlTalk1);
;
	jsr     decsp2
	lda     #$20
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_BigAlTalk1)
	ldx     #>(_BigAlTalk1)
	jsr     _oam_meta_spr
;
; if(moveframes >= 30 && moveframes < 61){
;
L0CF3:	lda     _moveframes
	cmp     #$1E
	bcc     L07B5
	cmp     #$3D
	bcs     L07B5
;
; oam_meta_spr(0x20, 0x20, BigAlTalk2);
;
	jsr     decsp2
	lda     #$20
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_BigAlTalk2)
	ldx     #>(_BigAlTalk2)
	jsr     _oam_meta_spr
;
; read_input();
;
L07B5:	jsr     _read_input
;
; if (trigger_clicked)
;
	lda     _trigger_clicked
	beq     L0CF8
;
; for(index=0; index < 10; ++index){
;
	lda     #$00
	sta     _index
L0CF7:	lda     _index
	cmp     #$0A
	bcs     L07C1
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; for(index=0; index < 10; ++index){
;
	inc     _index
	jmp     L0CF7
;
; init_mode_game();
;
L07C1:	jsr     _init_mode_game
;
; if(game_mode == MODE_GAME){
;
L0CF8:	lda     _game_mode
	cmp     #$01
	jne     L0CE9
;
; ppu_wait_nmi(); // wait till beginning of the frame
;
	jsr     _ppu_wait_nmi
;
; draw_level_one_sprites();
;
	jsr     _draw_level_one_sprites
;
; read_input(); //sets input_active
;
	jsr     _read_input
;
; if(trigger_pulled){
;
	lda     _trigger_pulled
	beq     L07CF
;
; started_pumping = 1; //actually only need to set this once
;
	lda     #$01
	sta     _started_pumping
;
; gas_speed += GAS_STEP;
;
	lda     #$32
	clc
	adc     _gas_speed
	sta     _gas_speed
	bcc     L07D8
	inc     _gas_speed+1
;
; while(gas_speed > 256){
;
	jmp     L07D8
;
; ++gas1;
;
L0CF9:	inc     _gas1
;
; gas_speed -= 256;
;
	lda     _gas_speed
	sec
	sbc     #$00
	sta     _gas_speed
	lda     _gas_speed+1
	sbc     #$01
	sta     _gas_speed+1
;
; while(gas_speed > 256){
;
L07D8:	lda     _gas_speed
	cmp     #$01
	lda     _gas_speed+1
	sbc     #$01
	bcs     L0CF9
;
; adjust_gas();
;
	jsr     _adjust_gas
;
; cost_speed += COST_STEP;
;
	lda     #$50
	clc
	adc     _cost_speed
	sta     _cost_speed
	bcc     L07E3
	inc     _cost_speed+1
;
; while(cost_speed > 256){
;
	jmp     L07E3
;
; ++cost1;
;
L0CFA:	inc     _cost1
;
; cost_speed -= 256;
;
	lda     _cost_speed
	sec
	sbc     #$00
	sta     _cost_speed
	lda     _cost_speed+1
	sbc     #$01
	sta     _cost_speed+1
;
; while(cost_speed > 256){
;
L07E3:	lda     _cost_speed
	cmp     #$01
	lda     _cost_speed+1
	sbc     #$01
	bcs     L0CFA
;
; adjust_cost(); 
;
	jsr     _adjust_cost
;
; } else {
;
	jmp     L07EA
;
; if(started_pumping == 1){
;
L07CF:	lda     _started_pumping
	cmp     #$01
	bne     L07EA
;
; init_level_one_end();
;
	jsr     _init_level_one_end
;
; draw_gas();
;
L07EA:	jsr     _draw_gas
;
; draw_cost();
;
	jsr     _draw_cost
;
; while (1){
;
	jmp     L0CE9

.endproc

