;this file for FamiTone2 library generated by text2data tool

gasjazz_music_data:
	.byte 11
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Title
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; IntroScroll
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; IntroCutscene
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; TalkingTime
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256 ; GasPump
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256 ; AbductionCutscene
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256 ; AlienTalkingTime
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256 ; AlienPump
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256 ; EndingSpace
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256 ; EndingScroll
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,307,256 ; AscentinOfZarkaq

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env4,@env0,@env8
	.byte $00
	.byte $70 ;instrument $04
	.word @env5,@env7,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env6,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cc,$c9,$c6,$00,$03
@env2:
	.byte $ce,$02,$cb,$c8,$00,$03
@env3:
	.byte $cf,$ce,$cb,$ca,$c9,$c7,$c4,$00,$06
@env4:
	.byte $c4,$00,$00
@env5:
	.byte $c8,$c4,$c2,$00,$02
@env6:
	.byte $cf,$ce,$cd,$cc,$cb,$cb,$ca,$ca,$c9,$c7,$c6,$c5,$c4,$c3,$c2,$c1
	.byte $00,$0f
@env7:
	.byte $c0,$c4,$cb,$00,$00
@env8:
	.byte $b8,$c3,$c3,$00,$02


; Title
@song0ch0:
	.byte $fb,$07
@song0ch0loop:
@ref0:
	.byte $80,$36,$85,$3c,$85,$44,$85,$3c,$85,$40,$85,$48,$85,$4e,$85,$48
	.byte $85,$32,$85,$3a,$85,$40,$85,$3a,$85,$32,$85,$3a,$85,$40,$85,$3a
	.byte $85
	.byte $fd
	.word @song0ch0loop

; Title
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $87,$82,$3c,$85,$4a,$95,$48,$85,$54,$95,$3a,$85,$48,$95,$3a,$85
	.byte $48,$8d
	.byte $fd
	.word @song0ch1loop

; Title
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; Title
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

; Title
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


; IntroScroll
@song1ch0:
	.byte $fb,$07
@song1ch0loop:
@ref5:
	.byte $86,$32,$8d,$44,$95,$40,$85,$3c,$9d,$3a,$85,$36,$85,$3a,$85,$32
	.byte $8d,$40,$85
	.byte $fd
	.word @song1ch0loop

; IntroScroll
@song1ch1:
@song1ch1loop:
@ref6:
	.byte $f9,$85
	.byte $fd
	.word @song1ch1loop

; IntroScroll
@song1ch2:
@song1ch2loop:
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song1ch2loop

; IntroScroll
@song1ch3:
@song1ch3loop:
@ref8:
	.byte $f9,$85
	.byte $fd
	.word @song1ch3loop

; IntroScroll
@song1ch4:
@song1ch4loop:
@ref9:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


; IntroCutscene
@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref10:
	.byte $80,$32,$85,$3c,$85,$40,$85,$36,$85,$32,$85,$44,$85,$40,$85,$3a
	.byte $85,$36,$85,$32,$85,$3a,$85,$44,$85,$40,$85,$36,$85,$32,$85,$3a
	.byte $85
	.byte $fd
	.word @song2ch0loop

; IntroCutscene
@song2ch1:
@song2ch1loop:
@ref11:
	.byte $f9,$85
	.byte $fd
	.word @song2ch1loop

; IntroCutscene
@song2ch2:
@song2ch2loop:
@ref12:
	.byte $80,$45,$40,$91,$37,$32,$91,$41,$45,$4a,$8d,$41,$3b,$36,$8d,$49
	.byte $3b,$37,$3b,$32,$8d
	.byte $fd
	.word @song2ch2loop

; IntroCutscene
@song2ch3:
@song2ch3loop:
@ref13:
	.byte $f9,$85
	.byte $fd
	.word @song2ch3loop

; IntroCutscene
@song2ch4:
@song2ch4loop:
@ref14:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop


; TalkingTime
@song3ch0:
	.byte $fb,$06
@song3ch0loop:
	.byte $ff,$20
	.word @ref0
	.byte $fd
	.word @song3ch0loop

; TalkingTime
@song3ch1:
@song3ch1loop:
	.byte $ff,$11
	.word @ref1
	.byte $fd
	.word @song3ch1loop

; TalkingTime
@song3ch2:
@song3ch2loop:
@ref17:
	.byte $84,$58,$95,$5c,$85,$4e,$a5,$58,$85,$5c,$8d,$4a,$9d
	.byte $fd
	.word @song3ch2loop

; TalkingTime
@song3ch3:
@song3ch3loop:
@ref18:
	.byte $f9,$85
	.byte $fd
	.word @song3ch3loop

; TalkingTime
@song3ch4:
@song3ch4loop:
@ref19:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop


; GasPump
@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref20:
	.byte $80,$32,$87,$3c,$83,$40,$87,$3c,$83,$32,$87,$3c,$83,$40,$87,$3c
	.byte $83,$28,$87,$32,$83,$36,$87,$32,$83,$28,$87,$32,$83,$36,$87,$32
	.byte $83
	.byte $fd
	.word @song4ch0loop

; GasPump
@song4ch1:
@song4ch1loop:
@ref21:
	.byte $f9,$85
	.byte $fd
	.word @song4ch1loop

; GasPump
@song4ch2:
@song4ch2loop:
@ref22:
	.byte $84,$5c,$95,$58,$85,$4e,$9d,$4a,$97,$54,$83,$58,$8d,$4e,$8d
	.byte $fd
	.word @song4ch2loop

; GasPump
@song4ch3:
@song4ch3loop:
@ref23:
	.byte $f9,$85
	.byte $fd
	.word @song4ch3loop

; GasPump
@song4ch4:
@song4ch4loop:
@ref24:
	.byte $f9,$85
	.byte $fd
	.word @song4ch4loop


; AbductionCutscene
@song5ch0:
	.byte $fb,$06
@song5ch0loop:
@ref25:
	.byte $86,$3a,$85,$40,$85,$46,$85,$40,$85,$42,$85,$40,$85,$3c,$85,$3a
	.byte $85,$44,$85,$40,$85,$3c,$85,$3a,$85,$38,$85,$36,$85,$38,$85,$34
	.byte $85
	.byte $fd
	.word @song5ch0loop

; AbductionCutscene
@song5ch1:
@song5ch1loop:
@ref26:
	.byte $f9,$85
	.byte $fd
	.word @song5ch1loop

; AbductionCutscene
@song5ch2:
@song5ch2loop:
@ref27:
	.byte $f9,$85
	.byte $fd
	.word @song5ch2loop

; AbductionCutscene
@song5ch3:
@song5ch3loop:
@ref28:
	.byte $f9,$85
	.byte $fd
	.word @song5ch3loop

; AbductionCutscene
@song5ch4:
@song5ch4loop:
@ref29:
	.byte $f9,$85
	.byte $fd
	.word @song5ch4loop


; AlienTalkingTime
@song6ch0:
	.byte $fb,$06
@song6ch0loop:
@ref30:
	.byte $88,$36,$85,$40,$85,$44,$85,$3c,$85,$40,$85,$48,$85,$4e,$85,$48
	.byte $85,$32,$85,$3a,$85,$40,$85,$3a,$85,$32,$85,$3a,$85,$40,$85,$3a
	.byte $85
	.byte $fd
	.word @song6ch0loop

; AlienTalkingTime
@song6ch1:
@song6ch1loop:
	.byte $ff,$11
	.word @ref1
	.byte $fd
	.word @song6ch1loop

; AlienTalkingTime
@song6ch2:
@song6ch2loop:
@ref32:
	.byte $88,$58,$95,$5c,$85,$4e,$a5,$58,$85,$5c,$8d,$4a,$9d
	.byte $fd
	.word @song6ch2loop

; AlienTalkingTime
@song6ch3:
@song6ch3loop:
@ref33:
	.byte $f9,$85
	.byte $fd
	.word @song6ch3loop

; AlienTalkingTime
@song6ch4:
@song6ch4loop:
@ref34:
	.byte $f9,$85
	.byte $fd
	.word @song6ch4loop


; AlienPump
@song7ch0:
	.byte $fb,$06
@song7ch0loop:
@ref35:
	.byte $8a,$4a,$85,$4a,$85,$4a,$85,$52,$85,$54,$85,$52,$85,$4e,$85,$4a
	.byte $85,$4a,$85,$4a,$85,$4a,$85,$54,$85,$58,$85,$54,$85,$58,$85,$4e
	.byte $85
	.byte $fd
	.word @song7ch0loop

; AlienPump
@song7ch1:
@song7ch1loop:
@ref36:
	.byte $f9,$85
	.byte $fd
	.word @song7ch1loop

; AlienPump
@song7ch2:
@song7ch2loop:
@ref37:
	.byte $8a,$33,$41,$45,$41,$37,$33,$3b,$41,$45,$45,$41,$45,$41,$45,$37
	.byte $33,$3b,$37,$33,$45,$41,$41,$37,$33,$3b,$41,$45,$33,$37,$33,$45
	.byte $32,$81
	.byte $fd
	.word @song7ch2loop

; AlienPump
@song7ch3:
@song7ch3loop:
@ref38:
	.byte $f9,$85
	.byte $fd
	.word @song7ch3loop

; AlienPump
@song7ch4:
@song7ch4loop:
@ref39:
	.byte $f9,$85
	.byte $fd
	.word @song7ch4loop


; EndingSpace
@song8ch0:
	.byte $fb,$06
@song8ch0loop:
@ref40:
	.byte $f9,$85
	.byte $fd
	.word @song8ch0loop

; EndingSpace
@song8ch1:
@song8ch1loop:
@ref41:
	.byte $8a,$3a,$85,$44,$85,$48,$85,$48,$85,$48,$85,$44,$85,$3c,$85,$3a
	.byte $85,$3a,$85,$44,$85,$48,$85,$48,$85,$48,$85,$44,$85,$40,$85,$3a
	.byte $85
	.byte $fd
	.word @song8ch1loop

; EndingSpace
@song8ch2:
@song8ch2loop:
@ref42:
	.byte $f9,$85
	.byte $fd
	.word @song8ch2loop

; EndingSpace
@song8ch3:
@song8ch3loop:
@ref43:
	.byte $f9,$85
	.byte $fd
	.word @song8ch3loop

; EndingSpace
@song8ch4:
@song8ch4loop:
@ref44:
	.byte $f9,$85
	.byte $fd
	.word @song8ch4loop


; EndingScroll
@song9ch0:
	.byte $fb,$06
@song9ch0loop:
@ref45:
	.byte $8c,$40,$85,$40,$85,$40,$85,$40,$85,$3c,$85,$32,$85,$32,$85,$32
	.byte $85,$32,$85,$3c,$85,$40,$85,$44,$85,$40,$85,$44,$85,$44,$85,$36
	.byte $85
	.byte $fd
	.word @song9ch0loop

; EndingScroll
@song9ch1:
@song9ch1loop:
@ref46:
	.byte $f9,$85
	.byte $fd
	.word @song9ch1loop

; EndingScroll
@song9ch2:
@song9ch2loop:
@ref47:
	.byte $f9,$85
	.byte $fd
	.word @song9ch2loop

; EndingScroll
@song9ch3:
@song9ch3loop:
@ref48:
	.byte $f9,$85
	.byte $fd
	.word @song9ch3loop

; EndingScroll
@song9ch4:
@song9ch4loop:
@ref49:
	.byte $f9,$85
	.byte $fd
	.word @song9ch4loop


; AscentinOfZarkaq
@song10ch0:
	.byte $fb,$06
@song10ch0loop:
@ref50:
	.byte $8c,$2c,$85,$3a,$85,$32,$85,$36,$85,$32,$85,$30,$85,$2c,$85,$2c
	.byte $85,$32,$85,$36,$85,$32,$85,$30,$85,$2c,$85,$3a,$85,$36,$85,$30
	.byte $85
	.byte $fd
	.word @song10ch0loop

; AscentinOfZarkaq
@song10ch1:
@song10ch1loop:
@ref51:
	.byte $f9,$85
	.byte $fd
	.word @song10ch1loop

; AscentinOfZarkaq
@song10ch2:
@song10ch2loop:
@ref52:
	.byte $f9,$85
	.byte $fd
	.word @song10ch2loop

; AscentinOfZarkaq
@song10ch3:
@song10ch3loop:
@ref53:
	.byte $f9,$85
	.byte $fd
	.word @song10ch3loop

; AscentinOfZarkaq
@song10ch4:
@song10ch4loop:
@ref54:
	.byte $f9,$85
	.byte $fd
	.word @song10ch4loop
