;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


gasjazz_music_data:
	.byte 11
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Title
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; IntroScroll
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; IntroCutscene
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; TalkingTime
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256 ; GasPump
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256 ; AbductionCutscene
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256 ; AlienTalkingTime
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256 ; AlienPump
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256 ; EndingSpace
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256 ; EndingScroll
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,307,256 ; AscentinOfZarkaq

@instruments:
	.word @env1,@env0,@env0,@env9
	.word @env2,@env0,@env0,@env9
	.word @env3,@env0,@env0,@env10
	.word @env4,@env0,@env8,@env11
	.word @env5,@env7,@env0,@env11
	.word @env5,@env0,@env0,@env0
	.word @env6,@env0,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cc,$c9,$c6,$00,$03
@env2:
	.byte $ce,$02,$cb,$c8,$00,$03
@env3:
	.byte $cf,$ce,$cb,$ca,$c9,$c7,$c4,$00,$06
@env4:
	.byte $c4,$00,$00
@env5:
	.byte $c8,$c4,$c2,$00,$02
@env6:
	.byte $cf,$ce,$cd,$cc,$cb,$cb,$ca,$ca,$c9,$c7,$c6,$c5,$c4,$c3,$c2,$c1
	.byte $00,$0f
@env7:
	.byte $c0,$c4,$cb,$00,$00
@env8:
	.byte $b8,$c3,$c3,$00,$02
@env9:
	.byte $c2,$00,$00
@env10:
	.byte $c3,$00,$00
@env11:
	.byte $c1,$c2,$00,$01


; Title
@song0ch0:
	.byte $fb,$07
@song0ch0loop:
@ref0:
	.byte $80,$1e,$85,$21,$85,$25,$85,$21,$85,$23,$85,$27,$85,$2a,$85,$27
	.byte $85,$1c,$85,$20,$85,$23,$85,$20,$85,$1c,$85,$20,$85,$23,$85,$20
	.byte $85
	.byte $fd
	.word @song0ch0loop

; Title
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $87,$82,$21,$85,$28,$95,$27,$85,$2d,$95,$20,$85,$27,$95,$20,$85
	.byte $27,$8d
	.byte $fd
	.word @song0ch1loop

; Title
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; Title
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

; Title
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


; IntroScroll
@song1ch0:
	.byte $fb,$07
@song1ch0loop:
@ref5:
	.byte $86,$1c,$8d,$25,$95,$23,$85,$21,$9d,$20,$85,$1e,$85,$20,$85,$1c
	.byte $8d,$23,$85
	.byte $fd
	.word @song1ch0loop

; IntroScroll
@song1ch1:
@song1ch1loop:
@ref6:
	.byte $f9,$85
	.byte $fd
	.word @song1ch1loop

; IntroScroll
@song1ch2:
@song1ch2loop:
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song1ch2loop

; IntroScroll
@song1ch3:
@song1ch3loop:
@ref8:
	.byte $f9,$85
	.byte $fd
	.word @song1ch3loop

; IntroScroll
@song1ch4:
@song1ch4loop:
@ref9:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


; IntroCutscene
@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref10:
	.byte $80,$1c,$85,$21,$85,$23,$85,$1e,$85,$1c,$85,$25,$85,$23,$85,$20
	.byte $85,$1e,$85,$1c,$85,$20,$85,$25,$85,$23,$85,$1e,$85,$1c,$85,$20
	.byte $85
	.byte $fd
	.word @song2ch0loop

; IntroCutscene
@song2ch1:
@song2ch1loop:
@ref11:
	.byte $f9,$85
	.byte $fd
	.word @song2ch1loop

; IntroCutscene
@song2ch2:
@song2ch2loop:
@ref12:
	.byte $80,$25,$81,$23,$91,$1e,$81,$1c,$91,$23,$81,$25,$81,$28,$8d,$23
	.byte $81,$20,$81,$1e,$8d,$27,$81,$20,$81,$1e,$81,$20,$81,$1c,$8d
	.byte $fd
	.word @song2ch2loop

; IntroCutscene
@song2ch3:
@song2ch3loop:
@ref13:
	.byte $f9,$85
	.byte $fd
	.word @song2ch3loop

; IntroCutscene
@song2ch4:
@song2ch4loop:
@ref14:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop


; TalkingTime
@song3ch0:
	.byte $fb,$06
@song3ch0loop:
	.byte $ff,$20
	.word @ref0
	.byte $fd
	.word @song3ch0loop

; TalkingTime
@song3ch1:
@song3ch1loop:
	.byte $ff,$11
	.word @ref1
	.byte $fd
	.word @song3ch1loop

; TalkingTime
@song3ch2:
@song3ch2loop:
@ref17:
	.byte $84,$2f,$95,$31,$85,$2a,$a5,$2f,$85,$31,$8d,$28,$9d
	.byte $fd
	.word @song3ch2loop

; TalkingTime
@song3ch3:
@song3ch3loop:
@ref18:
	.byte $f9,$85
	.byte $fd
	.word @song3ch3loop

; TalkingTime
@song3ch4:
@song3ch4loop:
@ref19:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop


; GasPump
@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref20:
	.byte $80,$1c,$87,$21,$83,$23,$87,$21,$83,$1c,$87,$21,$83,$23,$87,$21
	.byte $83,$17,$87,$1c,$83,$1e,$87,$1c,$83,$17,$87,$1c,$83,$1e,$87,$1c
	.byte $83
	.byte $fd
	.word @song4ch0loop

; GasPump
@song4ch1:
@song4ch1loop:
@ref21:
	.byte $f9,$85
	.byte $fd
	.word @song4ch1loop

; GasPump
@song4ch2:
@song4ch2loop:
@ref22:
	.byte $84,$31,$95,$2f,$85,$2a,$9d,$28,$97,$2d,$83,$2f,$8d,$2a,$8d
	.byte $fd
	.word @song4ch2loop

; GasPump
@song4ch3:
@song4ch3loop:
@ref23:
	.byte $f9,$85
	.byte $fd
	.word @song4ch3loop

; GasPump
@song4ch4:
@song4ch4loop:
@ref24:
	.byte $f9,$85
	.byte $fd
	.word @song4ch4loop


; AbductionCutscene
@song5ch0:
	.byte $fb,$06
@song5ch0loop:
@ref25:
	.byte $86,$20,$85,$23,$85,$26,$85,$23,$85,$24,$85,$23,$85,$21,$85,$20
	.byte $85,$25,$85,$23,$85,$21,$85,$20,$85,$1f,$85,$1e,$85,$1f,$85,$1d
	.byte $85
	.byte $fd
	.word @song5ch0loop

; AbductionCutscene
@song5ch1:
@song5ch1loop:
@ref26:
	.byte $f9,$85
	.byte $fd
	.word @song5ch1loop

; AbductionCutscene
@song5ch2:
@song5ch2loop:
@ref27:
	.byte $f9,$85
	.byte $fd
	.word @song5ch2loop

; AbductionCutscene
@song5ch3:
@song5ch3loop:
@ref28:
	.byte $f9,$85
	.byte $fd
	.word @song5ch3loop

; AbductionCutscene
@song5ch4:
@song5ch4loop:
@ref29:
	.byte $f9,$85
	.byte $fd
	.word @song5ch4loop


; AlienTalkingTime
@song6ch0:
	.byte $fb,$06
@song6ch0loop:
@ref30:
	.byte $88,$1e,$85,$23,$85,$25,$85,$21,$85,$23,$85,$27,$85,$2a,$85,$27
	.byte $85,$1c,$85,$20,$85,$23,$85,$20,$85,$1c,$85,$20,$85,$23,$85,$20
	.byte $85
	.byte $fd
	.word @song6ch0loop

; AlienTalkingTime
@song6ch1:
@song6ch1loop:
	.byte $ff,$11
	.word @ref1
	.byte $fd
	.word @song6ch1loop

; AlienTalkingTime
@song6ch2:
@song6ch2loop:
@ref32:
	.byte $88,$2f,$95,$31,$85,$2a,$a5,$2f,$85,$31,$8d,$28,$9d
	.byte $fd
	.word @song6ch2loop

; AlienTalkingTime
@song6ch3:
@song6ch3loop:
@ref33:
	.byte $f9,$85
	.byte $fd
	.word @song6ch3loop

; AlienTalkingTime
@song6ch4:
@song6ch4loop:
@ref34:
	.byte $f9,$85
	.byte $fd
	.word @song6ch4loop


; AlienPump
@song7ch0:
	.byte $fb,$06
@song7ch0loop:
@ref35:
	.byte $8a,$28,$85,$28,$85,$28,$85,$2c,$85,$2d,$85,$2c,$85,$2a,$85,$28
	.byte $85,$28,$85,$28,$85,$28,$85,$2d,$85,$2f,$85,$2d,$85,$2f,$85,$2a
	.byte $85
	.byte $fd
	.word @song7ch0loop

; AlienPump
@song7ch1:
@song7ch1loop:
@ref36:
	.byte $f9,$85
	.byte $fd
	.word @song7ch1loop

; AlienPump
@song7ch2:
@song7ch2loop:
@ref37:
	.byte $8a,$1c,$81,$23,$81,$25,$81,$23,$81,$1e,$81,$1c,$81,$20,$81,$23
	.byte $81,$25,$81,$25,$81,$23,$81,$25,$81,$23,$81,$25,$81,$1e,$81,$1c
	.byte $81,$20,$81,$1e,$81,$1c,$81,$25,$81,$23,$81,$23,$81,$1e,$81,$1c
	.byte $81,$20,$81,$23,$81,$25,$81,$1c,$81,$1e,$81,$1c,$81,$25,$81,$1c
	.byte $81
	.byte $fd
	.word @song7ch2loop

; AlienPump
@song7ch3:
@song7ch3loop:
@ref38:
	.byte $f9,$85
	.byte $fd
	.word @song7ch3loop

; AlienPump
@song7ch4:
@song7ch4loop:
@ref39:
	.byte $f9,$85
	.byte $fd
	.word @song7ch4loop


; EndingSpace
@song8ch0:
	.byte $fb,$06
@song8ch0loop:
@ref40:
	.byte $f9,$85
	.byte $fd
	.word @song8ch0loop

; EndingSpace
@song8ch1:
@song8ch1loop:
@ref41:
	.byte $8a,$20,$85,$25,$85,$27,$85,$27,$85,$27,$85,$25,$85,$21,$85,$20
	.byte $85,$20,$85,$25,$85,$27,$85,$27,$85,$27,$85,$25,$85,$23,$85,$20
	.byte $85
	.byte $fd
	.word @song8ch1loop

; EndingSpace
@song8ch2:
@song8ch2loop:
@ref42:
	.byte $f9,$85
	.byte $fd
	.word @song8ch2loop

; EndingSpace
@song8ch3:
@song8ch3loop:
@ref43:
	.byte $f9,$85
	.byte $fd
	.word @song8ch3loop

; EndingSpace
@song8ch4:
@song8ch4loop:
@ref44:
	.byte $f9,$85
	.byte $fd
	.word @song8ch4loop


; EndingScroll
@song9ch0:
	.byte $fb,$06
@song9ch0loop:
@ref45:
	.byte $8c,$23,$85,$23,$85,$23,$85,$23,$85,$21,$85,$1c,$85,$1c,$85,$1c
	.byte $85,$1c,$85,$21,$85,$23,$85,$25,$85,$23,$85,$25,$85,$25,$85,$1e
	.byte $85
	.byte $fd
	.word @song9ch0loop

; EndingScroll
@song9ch1:
@song9ch1loop:
@ref46:
	.byte $f9,$85
	.byte $fd
	.word @song9ch1loop

; EndingScroll
@song9ch2:
@song9ch2loop:
@ref47:
	.byte $f9,$85
	.byte $fd
	.word @song9ch2loop

; EndingScroll
@song9ch3:
@song9ch3loop:
@ref48:
	.byte $f9,$85
	.byte $fd
	.word @song9ch3loop

; EndingScroll
@song9ch4:
@song9ch4loop:
@ref49:
	.byte $f9,$85
	.byte $fd
	.word @song9ch4loop


; AscentinOfZarkaq
@song10ch0:
	.byte $fb,$06
@song10ch0loop:
@ref50:
	.byte $8c,$19,$85,$20,$85,$1c,$85,$1e,$85,$1c,$85,$1b,$85,$19,$85,$19
	.byte $85,$1c,$85,$1e,$85,$1c,$85,$1b,$85,$19,$85,$20,$85,$1e,$85,$1b
	.byte $85
	.byte $fd
	.word @song10ch0loop

; AscentinOfZarkaq
@song10ch1:
@song10ch1loop:
@ref51:
	.byte $f9,$85
	.byte $fd
	.word @song10ch1loop

; AscentinOfZarkaq
@song10ch2:
@song10ch2loop:
@ref52:
	.byte $f9,$85
	.byte $fd
	.word @song10ch2loop

; AscentinOfZarkaq
@song10ch3:
@song10ch3loop:
@ref53:
	.byte $f9,$85
	.byte $fd
	.word @song10ch3loop

; AscentinOfZarkaq
@song10ch4:
@song10ch4loop:
@ref54:
	.byte $f9,$85
	.byte $fd
	.word @song10ch4loop
